### ISSUE TITLE
Segfault with qt >=4.8.6 on ubuntu

### ISSUE THREAD

**Issue by swt30** [JuliaPy/PyPlot.jl#234]
I updated my (systemwide) miniconda installation but now PyPlot is in trouble:

```
julia> using PyPlot

julia> plot(1:10, randn(10))

signal(11): Segmentation fault
unknown function (ip: 0x32736)
unknown function (ip: (nil))
[1]    4493 segmentation fault: julia
```

The issue remains with a fresh installation of PyPlot and `ENV["PYTHON"] = ""` to ensure that a fresh download of Conda.jl is used instead. But everything is fine if I plot from Python directly. I'm using julia 0.4.6 on Linux x86_64 (ubuntu 16.04).

Anything I can do to diagnose this further?

**Comment by stevengj** [comment]
Can you try `Pkg.checkout("PyCall"); Pkg.build("PyCall")` to see if the problem persists with PyCall master?

**Comment by stevengj** [comment]
Or actually maybe you just need to re-run `Pkg.build("PyCall")`.

**Comment by swt30** [comment]
Problem still persists - here's a [backtrace](https://gist.github.com/swt30/d0730b6ac75ed05c7ef4e9cdf831e0f7).

**Comment by swt30** [comment]
OK, downgrading python/qt/sip works: 

```
$ conda install python=3.4 pyqt=4.10

[...]

The following packages will be DOWNGRADED due to dependency conflicts:

    pyqt:            4.11.4-py35_4     --> 4.10.4-py34_0    
    python:          3.5.2-0           --> 3.4.5-0          
    qt:              4.8.7-4           --> 4.8.5-0          
    sip:             4.18-py35_0       --> 4.15.5-py34_0    
```

The problem therefore appeared somewhere in these updates.

**Comment by stevengj** [comment]
Are you using the same backend (qt) in Julia and Python?

**Comment by swt30** [comment]
Yes I am.

```
julia> using PyPlot

julia> pygui(:qt)
:qt

julia> figure()

signal (11): Segmentation fault
unknown function (ip: 0x32736)
unknown function (ip: (nil))
[1]    27445 segmentation fault  julia
~❯ ipython
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %pylab qt
Populating the interactive namespace from numpy and matplotlib

In [2]: figure()
Out[2]: <matplotlib.figure.Figure at 0x7f06a03d4940>
```

That's again using a system miniconda install, but same thing if I let Conda do it.

**Comment by stevengj** [comment]
What happens if you use a different backend, e.g. tk?

**Comment by swt30** [comment]
Same thing:

```
julia> using PyPlot

julia> pygui(:tk)
:tk

julia> figure()

signal (11): Segmentation fault
unknown function (ip: 0x32736)
unknown function (ip: (nil))
[1]    2100 segmentation fault  julia
~❯ ipython
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %pylab tk
Populating the interactive namespace from numpy and matplotlib

In [2]: figure()
Out[2]: <matplotlib.figure.Figure at 0x7fdcc3686390>
```

**Comment by swt30** [comment]
Works fine:

```
julia> using PyCall

julia> pygui(:tk)
:tk

julia> using PyPlot

julia> figure()
PyPlot.Figure(PyObject <matplotlib.figure.Figure object at 0x7f9a9baf2780>)
```

**Comment by stevengj** [comment]
That's helpful, so it is something about the way we are calling Qt (presumably the event loop in PyCall/src/gui.jl that doesn't work any more...)

What happens if you just start the Qt event loop?  `using PyCall; pygui_start(:qt)`.

**Comment by swt30** [comment]
That also works just fine.

**Comment by stevengj** [comment]
Does Conda with Python2 work?

**Comment by swt30** [comment]
No. When I tested it with Conda.jl, which uses Python 2, it didn't work with the newer Qt either. 

If anyone reads this and needs a temporary workaround, you should be able to do `Conda.add("pyqt=4.10")` to downgrade your version of pyqt.

**Comment by stevengj** [comment]
Just tried it on MacOS and PyPlot is working fine with Conda and pyqt-4.11.4, so it may be something specific to Linux.

**Comment by swt30** [comment]
I've been able to run it successfully on a different Linux box, so it's only specific to my machine at the moment :/

**Comment by stevengj** [comment]
Ah, maybe its a conflict in your library paths somehow?  Maybe you have multiple `libqt` libraries installed and the system is getting confused about which one to load or something?

**Comment by swt30** [comment]
I don't believe I have any other libqt libraries installed. The only place seems to be in the conda directory. I've confirmed that the crash is related to the version of `qt` in the conda environment: it happens for version 4.8.6 and above.

**Comment by lopezm94** [comment]
This happens to me aswell, but it dissapear by running julia with root permission

**Comment by swt30** [comment]
Huh - yes I can confirm that running julia as root also gets around this.

**Comment by lopezm94** [comment]
Would be nice a to have a fix for this though, `Plots.jl` has this as a dependency

**Comment by tbreloff** [comment]
> Plots.jl has this as a dependency

No it doesn't

**Comment by lopezm94** [comment]
Sorry, I meant uses it as default backend.

**Comment by tbreloff** [comment]
Just for the record, I have this exact same issue.  This crashes (normal Conda.jl install):

```
using PyPlot
plot(rand(10))
```

This works:

```
using PyCall
pygui(:tk)
using PyPlot
plot(rand(10))
```

and this works as well:

```
import Conda
Conda.add("qt=4.8.5")
using PyPlot
plot(rand(10))
```

I'm on Ubuntu: 

```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc0+111 (2016-08-01 19:26 UTC)
 _/ |\__'_|_|_|\__'_|  |  tb_pkgsha/7f3e776 (fork: 1 commits, 1 day)
|__/                   |  x86_64-linux-gnu
```

```
 - PyCall                        1.6.3
 - PyPlot                        2.2.0+   985eb4bb  master
 - Conda                         0.2.2
```

**Comment by stevengj** [comment]
Here is the [list of changes](http://qtmirror.ics.com/pub/qtproject/official_releases/qt/4.8/4.8.6/changes-4.8.6) in 4.8.6 compared to 4.8.5.   Nothing jumps out at me at first glance, though.

**Comment by krisztiankosi** [comment]
I had a same problem. My solution was: 
installed matplotlib from the ubuntu repo (followed by this site)
`http://scipy.org/install.html`

`sudo apt-get install python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose`

After I reinstalled PyPlot, and it works fine.

**Comment by swt30** [comment]
Ubuntu repositories usually lag the latest version, so it's quite possible that the version of Qt you get from the repositories is 4.8.5 or earlier. It may still break in future.

I also don't see anything in the change log that jumps out. The advice I've seen for other problems with Qt is along the lines of "move to Qt5 as this is being actively developed" - is it worth trying it instead of Qt4?

**Comment by stevengj** [comment]
We should certainly support the qt5 backend, but we can't stop people from specifying the qt4 backend.

**Comment by swt30** [comment]
I'm worried that this issue is going to result in a bad first impression: 0.5 is released, a wave of people try it out, install PyPlot or Plots, get a segfault and swamp you and @tbreloff with complaints! But I don't know how one goes about understanding the cause of a segfault. I guess with Gallium up and running now it might be worth stepping through and seeing where the error occurs.

**Comment by stevengj** [comment]
Well, the default backend is `tk`, so doesn't this only affect people if they (a) have the newer qt and (b) specify the qt backend in their `.matplotlibrc`?

@krisztiankosi's experience suggests that there may be some problem with matplotlib after all — if upgrading matplotlib fixes the problem, hopefully this will go away once Ubuntu has a newer matplotlib?

**Comment by stevengj** [comment]
@krisztiankosi, are you still using the qt backend?  (Look at `PyPlot.backend`)

**Comment by tbreloff** [comment]
> the default backend is tk, so doesn't this only affect people if they (a) have the newer qt and (b) specify the qt backend in their .matplotlibrc?

I'm not sure if this is true.  I think mine defaults to pyqt4?  I never set anything in the .matplotlibrc, so it's using a default value from somewhere.   I'm not at my ubuntu desktop right now so I can't check.

**Comment by stevengj** [comment]
@tbreloff, it tries [tk, then gtk, then qt](https://github.com/stevengj/PyPlot.jl/blob/06e800c4458279a17fc957a80988bb3d0fddd7e5/src/PyPlot.jl#L102-L103).  Maybe the tk and gtk backends are not installed on Ubuntu?

**Comment by andyferris** [comment]
I'm also getting this issue on Ubuntu 16.04. Explicitly using tk works, so it is definitely installed, but it will default to qt. (I'm sure I have qt5 installed on my machine, too.) Downgrading qt with `Conda` also works.

**Comment by stevengj** [comment]
I'm confused about why it is defaulting to `qt`.   What does
```jl
using PyCall
matplotlib = pyimport("matplotlib")
rcParams = PyDict(matplotlib["rcParams"])
default = lowercase(get(ENV, "MPLBACKEND", get(rcParams, "backend", "none")))
```
give?

**Comment by andyferris** [comment]
```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc2+1 (2016-08-18 20:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit d259be5 (4 days old release-0.5)
|__/                   |  x86_64-linux-gnu

julia> using PyCall

julia> matplotlib = pyimport("matplotlib")
PyObject <module 'matplotlib' from '/home/ferris/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/__init__.pyc'>

julia> rcParams = PyDict(matplotlib["rcParams"])
PyCall.PyDict{PyCall.PyAny,PyCall.PyAny} with 249 entries:
  "animation.frame_format"        => "png"
  "axes.spines.right"             => true
  "figure.subplot.right"          => 0.9
  "mathtext.cal"                  => "cursive"
  "font.fantasy"                  => Any["Comic Sans MS","Chicago","Charcoal","…
  "grid.alpha"                    => 1.0
  "xtick.minor.pad"               => 4.0
  "boxplot.medianprops.linestyle" => "-"
  "boxplot.flierprops.linewidth"  => 1.0
  "image.aspect"                  => "equal"
  "lines.markeredgewidth"         => 0.5
  "boxplot.whiskerprops.color"    => "b"
  "contour.corner_mask"           => true
  "figure.subplot.hspace"         => 0.2
  "keymap.fullscreen"             => Any["f","ctrl+f"]
  "examples.directory"            => ""
  "xtick.direction"               => "in"
  "axes.facecolor"                => "w"
  "mathtext.fontset"              => "cm"
  ⋮                               => ⋮

julia> default = lowercase(get(ENV, "MPLBACKEND", get(rcParams, "backend", "none")))
"qt4agg"
```

**Comment by stevengj** [comment]
So `get(rcParams, "backend", "none")` is `qt4agg`?   i.e. either you have a `.matplotlibrc` file that is setting this default, or there is a system-wide matplotlibrc?

**Comment by aytekinar** [comment]
I have the same problem on Arch Linux. I have a `.config/matplotlib/matplotlibrc` file which sets the backend for my user session. I have segfaults with `qt5agg` and `tkagg`. Any suggestions?

**Comment by swt30** [comment]
Looks like there's a matplotlibrc file in `INSTALL_LOCATION/matplotlib/mpl-data/matplotlibrc` (http://matplotlib.org/users/customizing.html). It sets the backend to qt4agg on both my Ubuntu and Red Hat machines. But only the Ubuntu machine has this problem.

**Comment by deszoeke** [comment]
My MPLBACKEND is qt4agg and it crashes on CentOS 7:
```
julia> plot(1:5)
Cannot mix incompatible Qt library (version 0x40805) with this library (version 0x40807)

signal (6): Aborted
gsignal at /usr/bin/../lib64/libc.so.6 (unknown line)
abort at /usr/bin/../lib64/libc.so.6 (unknown line)
_Z17qt_message_output9QtMsgTypePKc at /home/server/pi/homes/sdeszoek/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/PyQt4/../../../libQtCore.so.4 (unknown line)
unknown function (ip: 0x7f11b3c8b6fc)
_Z6qFatalPKcz at /home/server/pi/homes/sdeszoek/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/PyQt4/../../../libQtCore.so.4 (unknown line)
_ZN14QObjectPrivateC2Ei at /home/server/pi/homes/sdeszoek/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/PyQt4/../../../libQtCore.so.4 (unknown line)
unknown function (ip: 0x7f118deba762)
_ZN22QDBusAbstractInterfaceC2ERK7QStringS2_PKcRK15QDBusConnectionP7QObject at /usr/bin/../lib64/libQtDBus.so.4 (unknown line)
_ZN24QDBusConnectionInterfaceC1ERK15QDBusConnectionP7QObject at /usr/bin/../lib64/libQtDBus.so.4 (unknown line)
unknown function (ip: 0x7f118de9e095)
_ZN15QDBusConnection12connectToBusENS_7BusTypeERK7QString at /usr/bin/../lib64/libQtDBus.so.4 (unknown line)
_ZN15QDBusConnection10sessionBusEv at /usr/bin/../lib64/libQtDBus.so.4 (unknown line)
unknown function (ip: 0x7f11982b4302)
unknown function (ip: 0x7f11982c011a)
_ZN13QStyleFactory6createERK7QString at /home/server/pi/homes/sdeszoek/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/PyQt4/../../../libQtGui.so.4 (unknown line)
_ZN12QApplication5styleEv at /home/server/pi/homes/sdeszoek/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/PyQt4/../../../libQtGui.so.4 (unknown line)
_ZN19QApplicationPrivate10initializeEv at /home/server/pi/homes/sdeszoek/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/PyQt4/../../../libQtGui.so.4 (unknown line)
_ZN19QApplicationPrivate9constructEP9_XDisplaymm at /home/server/pi/homes/sdeszoek/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/PyQt4/../../../libQtGui.so.4 (unknown line)
_ZN12QApplicationC2ERiPPci at /home/server/pi/homes/sdeszoek/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/PyQt4/../../../libQtGui.so.4 (unknown line)
unknown function (ip: 0x7f11aecbf5ce)
unknown function (ip: 0x7f11aecbf6d1)
unknown function (ip: 0x7f11b8a492f8)
type_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/typeobject.c:763
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
do_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4567
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
fast_function at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4445
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
function_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/funcobject.c:533
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
instancemethod_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/classobject.c:2603
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
do_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4567
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
function_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/funcobject.c:533
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
instancemethod_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/classobject.c:2603
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
slot_tp_init at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/typeobject.c:5778
type_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/typeobject.c:763
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
do_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4567
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
fast_function at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4445
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
function_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/funcobject.c:530
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
ext_do_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:4664
PyEval_EvalCodeEx at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Python/ceval.c:3582
function_call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/funcobject.c:533
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
pycall at /home/server/pi/homes/sdeszoek/.julia/v0.4/PyCall/src/exception.jl:78
figure at /home/server/pi/homes/sdeszoek/.julia/v0.4/PyPlot/src/PyPlot.jl:366
julia_figure_22626 at  (unknown line)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
jl_f_apply at /usr/bin/../lib64/julia/libjulia.so (unknown line)
jl_Function_call at /home/server/pi/homes/sdeszoek/.julia/v0.4/PyCall/src/callback.jl:35
jlcapi_jl_Function_call_21951 at  (unknown line)
PyObject_Call at /home/ilan/minonda/conda-bld/work/Python-2.7.12/Objects/abstract.c:2546
unknown function (ip: 0x7f13ebb65241)

Abort (core dumped)
```

**Comment by stevengj** [comment]
If you edit `PyCall/src/gui.jl` to make `qt_eventloop` into the following:
```
function qt_eventloop(QtModule="PyQt4", sec::Real=50e-3)
    QtCore = pyimport("$QtModule.QtCore")
    app = pycall(QtCore["QCoreApplication"]["instance"], PyObject)
    AllEvents = QtCore["QEventLoop"]["AllEvents"]
    processEvents = QtCore["QCoreApplication"]["processEvents"]
    maxtime = PyObject(50)
    @doevent begin
        app["_in_event_loop"] = true
        pycall(processEvents, PyObject, AllEvents, maxtime)
    end
    install_doevent(doevent, sec)
end
```
does that fix it?

**Comment by swt30** [comment]
No, and I now get this error upon `using PyPlot`

```jl
julia> using PyPlot
INFO: Recompiling stale cache file /home/sthomas/.julia/lib/v0.5/PyCall.ji for module PyCall.
INFO: Recompiling stale cache file /home/sthomas/.julia/lib/v0.5/PyPlot.ji for module PyPlot.

julia> ERROR (unhandled task failure): KeyError: key "_in_event_loop" not found
 at setindex!(::PyCall.PyObject, ::Bool, ::String) at PyCall.jl:274
 at doevent at gui.jl:111 [inlined]
 at (::Base.##349#350{PyCall.#doevent#2{PyCall.PyObject,PyCall.PyObject,PyCall.PyObject,PyCall.PyObject},Timer})() at event.jl:384
```

**Comment by cedeerwe** [comment]
Just for the record, I am still experiencing the same issue with a fresh ubuntu 16.04, and fresh julia (Version 0.4.6 (2016-06-19 17:16 UTC)) and PyPlot installed according to the instructions.

The snippet
```using PyCall; pygui(:tk); using PyPlot```
works just fine.

**Comment by aytekinar** [comment]
Not sure the issue is related to this thread, but I do confirm that installing Julia against Intel libraries (Parallel Studio XE 2016 and 2017, both, to be precise) in Arch Linux results in segfaults when trying to plot. However, the official package provided by Arch Linux (i.e., `sudo pacman -S julia`) does work properly.

I also can confirm, in the Intel case, that installing `PyPlot` the `Conda` way or using the provided `python` within the system does not change the end result.

**Comment by stevengj** [comment]
@aytekinar, that is probably unrelated.  Probably in that case you have conflicting BLAS libraries, similar to #100.

**Comment by aytekinar** [comment]
@stevengj I wanted to comment here, as up in this thread I previously mentioned about a problem regarding `PyPlot`. Now, I do not have this problem. However, I have noticed also that `pygui()` returns `:tk` even though my `.matplotlibrc` file favours `Qt5Agg`.

P.S: Thanks for the reference. I will read the thread.

**Comment by stevengj** [comment]
@aytekinar, that is #244.  In a Github issue, you should not ask questions about unrelated issues.

**Comment by aytekinar** [comment]
@stevengj, with all due respect, I think we are having a hard time understanding each other. I do know what issues are and which issue relates to which one.

If you notice, my first comment above
> I have the same problem on Arch Linux. I have a .config/matplotlib/matplotlibrc file which sets the backend for my user session. I have segfaults with qt5agg and tkagg. Any suggestions?

back in late August was indeed related to this topic. #244 was opened 5 days ago, right? Changing the backend to any other, or removing the `.matplotlibrc` from my dot-config folder, back then, was a no go. However, now I can see that the problem was not related to my system (Arch Linux), but to how I had installed Julia using Intel compilers.

What I meant today by
> @stevengj I wanted to comment here, as up in this thread I previously mentioned about a problem regarding PyPlot. Now, I do not have this problem. However, I have noticed also that pygui() returns :tk even though my .matplotlibrc file favours Qt5Agg.

was supposed to convey the information that the very first post of mine could be discarded (if you are keeping a record of platform/issue matrix where `PyPlot` fails, for instance, such as `Ubuntu with XXX configuration`, `Arch Linux with YYY configuration`) as it were related to Intel binaries.

Apologies for the long post. Cheers!

**Comment by swt30** [comment]
It's years later, Julia has moved on and PythonPlot is now a thing, and I'm tidying my active issues, so I'll close this.
