### ISSUE TITLE
withfig does not work on 0.5rc3

### ISSUE THREAD

**Issue by dpsanders** [JuliaPy/PyPlot.jl#240]
(Found by @alanedelman)

```julia
fig = figure()

x = -5:0.01:5

@manipulate for i in 1:10
    withfig(fig) do
        plot(x, x*i)
    end
end
```

gives
```julia
LoadError: MethodError: no method matching withfig(::##31#33{Int64}, ::PyCall.PyObject)
Closest candidates are:
  withfig(::Function, !Matched::PyPlot.Figure; clear) at /Users/dpsanders/.julia/v0.5/PyPlot/src/PyPlot.jl:548
while loading In[2], in expression starting on line 5

 at (::##30#32)(::Int64) at In[2]:6
 at map(::Function, ::Reactive.Signal{Int64}) at operators.jl:29
```

since `figure()` no longer returns a `PyPlot.Figure` object.

```julia
versioninfo()
Julia Version 0.5.0-rc3+0
Commit e6f843b (2016-08-22 23:43 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by stevengj** [comment]
Should be fixed in PyCall master by JuliaPy/PyCall.jl/commit/869db2838fd0df0033fa6305d6ce72c9f65d5866

...

The weird thing is that I "fixed" the issue just by moving some definitions out of a `let` block so that I could see them.   Furthermore, the old code worked-as is in Julia 0.6.  @tkelman, is there a bug fix in 0.6 (hopefully pending backport to 0.5) that would have avoided the need for the above commit?

**Comment by tkelman** [comment]
No idea. Bisect?

**Comment by dpsanders** [comment]
Confirmed fixed by checkout out PyCall master. Could you tag a new version please? Course in 15 mins...

**Comment by andreasnoack** [comment]
Running `PyCall.pytype_mapping(plt[:Figure], PyPlot.Figure)` again also seemed to fix the issue. No idea why.

**Comment by stevengj** [comment]
@andreasnoack, yes, I notice that. It's clearly a Julia bug in 0.5 (but not 0.4 or 0.6).   I'll try to see if I can bisect it, but it will probably have to wait until the weekend.
