### ISSUE TITLE
plots in external qt4 window do not get updated 

### ISSUE THREAD

**Issue by gasagna** [JuliaPy/PyPlot.jl#245]
Hi,

something must have happened in the last few weeks. The problem occurs in combination with IJulia, on Julia v0.4. Basically the first call to plotting functions works fine and the plot gets displayed in its own window. Subsequent calls to the same functions (and also `clf()`) have not effect, **unless** I call `draw()` to update manually the figure, or I use the pan tool, which probably triggers the redraw.

This behaviour disappears if after the usual call to 
````julia
using PyPlot; pygui(true)
````
I call `ion()`. Then, I do not need to manually update the figure.

I am using matplotlib 1.5.1, Julia 1.3.1, PyPlot 2.2.2 and Pycall 1.7.2.

**Comment by stevengj** [comment]
Should be fixed now, thanks.

**Comment by gasagna** [comment]
Thanks for fixing this quickly!
