### ISSUE TITLE
Update to PyQt5 for Conda broke Anaconda support (for now)

### ISSUE THREAD

**Issue by oschulz** [JuliaPy/PyPlot.jl#247]
Since 42b66ee it's apparently currently not possible to use PyPlot with Anaconda, due to ContinuumIO/anaconda-issues#1068. While this is primarily an Anaconda issue (hopefully fixed in the not too distant future), it would still be nice if PyPlot could keep backward compatibility for Anaconda installs with matplotlib+qt4. Users may, for example, not even have write privileges to change/update Anaconda, with shared/central installations on bigger systems (e.g. compute clusters).

**Comment by stevengj** [comment]
Should be fixed by #246; do a Pkg.update again.

**Comment by oschulz** [comment]
Wow, that fix was even faster than my issue - thanks, @tkelman ! Should have tried master again before reporting, sorry.
