### ISSUE TITLE
Segmentation fault when using PyPlot after calling workspace()

### ISSUE THREAD

**Issue by novatena** [JuliaPy/PyPlot.jl#250]
Hello,

Following code sequence will introduce segmentation fault:

```
using PyPlot
workspace()
using PyPlot
```

This issue doesn't happen for other pkgs, e.g. JuMP.
```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)


``````
WARNING: Method definition redirect_stderr(Function, Any) in module Compat at /home/nova/.julia/v0.5/Compat/src/Compat.jl:1597 overwritten in module Compat at /home/nova/.julia/v0.5/Compat/src/Compat.jl:1597.
WARNING: Method definition redirect_stdout(Function, Any) in module Compat at /home/nova/.julia/v0.5/Compat/src/Compat.jl:1597 overwritten in module Compat at /home/nova/.julia/v0.5/Compat/src/Compat.jl:1597.
WARNING: Method definition redirect_stdin(Function, Any) in module Compat at /home/nova/.julia/v0.5/Compat/src/Compat.jl:1597 overwritten in module Compat at /home/nova/.julia/v0.5/Compat/src/Compat.jl:1597.
WARNING: Method definition macroexpand(Module, Any) in module MacroTools at /home/nova/.julia/v0.5/MacroTools/src/utils.jl:60 overwritten in module MacroTools at /home/nova/.julia/v0.5/MacroTools/src/utils.jl:60.
WARNING: Method definition run(Function) in module BinDeps at /home/nova/.julia/v0.5/BinDeps/src/BinDeps.jl:445 overwritten in module BinDeps at /home/nova/.julia/v0.5/BinDeps/src/BinDeps.jl:445.

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
julia_type_to_llvm at /home/centos/buildbot/slave/package_tarball64/build/src/cgutils.cpp:318
mark_julia_const at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:641
emit_expr at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:3140
emit_function at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:4691
jl_compile_linfo at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:809
emit_invoke at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:2684 [inlined]
emit_expr at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:3162
emit_assignment at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:2977 [inlined]
emit_expr at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:3185
emit_stmtpos at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:3064
emit_function at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:4727
jl_compile_linfo at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:809
emit_invoke at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:2684 [inlined]
emit_expr at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:3162
emit_assignment at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:2977 [inlined]
emit_expr at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:3185
emit_stmtpos at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:3064
emit_function at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:4727
jl_compile_linfo at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:809
emit_invoke at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:2684 [inlined]
emit_expr at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:3162
emit_call at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:2750
emit_expr at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:3172
emit_stmtpos at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:3064
emit_function at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:4727
jl_compile_linfo at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:809
jl_compile_for_dispatch at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1310
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:184 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
jl_module_run_initializer at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:83
jl_init_restored_modules at /home/centos/buildbot/slave/package_tarball64/build/src/dump.c:1994 [inlined]
_jl_restore_incremental at /home/centos/buildbot/slave/package_tarball64/build/src/dump.c:2560
_jl_restore_incremental at /home/centos/buildbot/slave/package_tarball64/build/src/dump.c:2498 [inlined]
jl_restore_incremental at /home/centos/buildbot/slave/package_tarball64/build/src/dump.c:2580
_include_from_serialized at ./loading.jl:150
_require_from_serialized at ./loading.jl:187
_require_search_from_serialized at ./loading.jl:217
unknown function (ip: 0x7efdce27c490)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
require at ./loading.jl:371
unknown function (ip: 0x7efdce17ab8b)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
read_verify_mod_list at /home/centos/buildbot/slave/package_tarball64/build/src/dump.c:1843
_jl_restore_incremental at /home/centos/buildbot/slave/package_tarball64/build/src/dump.c:2514
_jl_restore_incremental at /home/centos/buildbot/slave/package_tarball64/build/src/dump.c:2498 [inlined]
jl_restore_incremental at /home/centos/buildbot/slave/package_tarball64/build/src/dump.c:2580
_include_from_serialized at ./loading.jl:150
_require_from_serialized at ./loading.jl:187
_require_search_from_serialized at ./loading.jl:217
unknown function (ip: 0x7efdce27c490)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
require at ./loading.jl:371
unknown function (ip: 0x7efdce17ab8b)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
eval_import_path_ at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:402
eval_import_path at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:429 [inlined]
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:480 [inlined]
jl_toplevel_eval at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:580
jl_toplevel_eval_in_warn at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:590
eval at ./boot.jl:234
unknown function (ip: 0x7efdce12b4df)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
eval_user_input at ./REPL.jl:64
unknown function (ip: 0x7efbbbc96d96)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
macro expansion at ./REPL.jl:95 [inlined]
#3 at ./event.jl:68
unknown function (ip: 0x7efbbbc93f2f)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
start_task at /home/centos/buildbot/slave/package_tarball64/build/src/task.c:253
unknown function (ip: 0xffffffffffffffff)
Allocations: 5271615 (Pool: 5270479; Big: 1136); GC: 7
Segmentation fault (core dumped)
```

**Comment by gaika** [comment]
Gives a lot of warnings but doesn't crash on v0.4.7, crashes on v0.5 and v0.6

**Comment by stevengj** [comment]
`using PyCall; workspace(); using PyCall` triggers the crash, so it is not PyPlot per se.

**Comment by stevengj** [comment]
Closing in favor of JuliaPy/PyCall.jl#325
