### ISSUE TITLE
PyPlot crashes with Julia 0.5

### ISSUE THREAD

**Issue by ehsantn** [JuliaPy/PyPlot.jl#256]
PyPlot crashes with just `fig, ax = subplots()` on Julia 0.5 ([backtrace](https://gist.github.com/ehsantn/a12e286f2dcb37b7661594aa4bf5dd66.js)). I have tried Ubuntu 16.04 and Centos 7 with Python 2.7 and 3.5 (default and Anaconda distributions). The problem seems related to matrix multiply.

**Comment by stevengj** [comment]
Are you using Julia compiled with the Intel MKL math libraries?  These have a known conflict if NumPy is not compiled with the same MKL libraries (which provide matrix multiplies); it is better to use the default Julia download (compiled with OpenBLAS).  (See JuliaPy/PyCall.jl#65)

**Comment by ehsantn** [comment]
Thanks, this solved the issue.
