### ISSUE TITLE
Using LaTeX plot labels syntax L"$...$" fails when used in plot legend

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [JuliaPy/PyPlot.jl#265]
### Overview
This is a follow up form [this issue](https://github.com/JuliaLang/julia/issues/19676). It occures when using L"$...$" syntax in plot legend.

### Minimal working example
```
using PyPlot
plot(1:10,rand(10,1))
legend(L"$α$")
```
The legend label comes up as "$" as opposed to "α" (see screenshot). The following do not work either: `legend(L"$\alpha$")`, `legend(L"\alpha")` or `legend(L"α")`

### Versioninfo
Here is my `versioninfo()`
```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

### Screenshot
![image](https://cloud.githubusercontent.com/assets/24707398/21430430/21943388-c85b-11e6-8d46-9e9812eadcb7.png)

**Comment by stevengj** [comment]
The `legend` argument needs to be an array: `legend([L"\alpha"])`
