### ISSUE TITLE
Fails to compile julia-0.6?

### ISSUE THREAD

**Issue by nbecker** [JuliaPy/PyPlot.jl#266]
using PyPlot
INFO: Precompiling module PyPlot.
ERROR: LoadError: InitError: UndefVarError: name not defined
 in macro expansion at /home/nbecker/.julia/v0.6/PyCall/src/exception.jl:78 [inlined]
 in pyimport(::String) at /home/nbecker/.julia/v0.6/PyCall/src/PyCall.jl:387
 in __init__() at /home/nbecker/.julia/v0.6/PyCall/src/pyinit.jl:58
 in anonymous at ./<missing>:2
during initialization of module PyCall
while loading /home/nbecker/.julia/v0.6/PyPlot/src/PyPlot.jl, in expression starting on line 5
ERROR: Failed to precompile PyPlot to /home/nbecker/.julia/lib/v0.6/PyPlot.ji.
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 in macro expansion at ./REPL.jl:97 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:66

julia-0.6.0-0.20161214.fc25.x86_64

**Comment by musm** [comment]
I also get this error

**Comment by musm** [comment]
Looks like this is  a macro hygiene problem in Pycall and you need to run `Pkg.checkout("PyCall")`. Latest PyCall master has this fixed.

**Comment by nbecker** [comment]
Seems like it now compiles, but I have a new problem:
> plot(real(xconst), "x-")
ERROR: PyError (:PyObject_Call) <class 'TypeError'>
TypeError("__init__() missing 1 required positional argument: 'figure'",)
  File
"/home/nbecker/.local/lib/python3.5/site-packages/matplotlib/pyplot.py",
line 3306, in plot
    ax = gca()
  File
"/home/nbecker/.local/lib/python3.5/site-packages/matplotlib/pyplot.py",
line 949, in gca
    return gcf().gca(**kwargs)
  File
"/home/nbecker/.local/lib/python3.5/site-packages/matplotlib/pyplot.py",
line 586, in gcf
    return figure()
  File
"/home/nbecker/.local/lib/python3.5/site-packages/matplotlib/pyplot.py",
line 535, in figure
    **kwargs)
  File
"/home/nbecker/.local/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py",
line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File
"/home/nbecker/.local/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py",
line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File
"/home/nbecker/.local/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py",
line 76, in __init__
    FigureCanvasQT.__init__(self, figure)
  File
"/home/nbecker/.local/lib/python3.5/site-packages/matplotlib/backends/backend_qt4.py",
line 66, in __init__
    QtWidgets.QWidget.__init__(self)

 in pyerr_check at /home/nbecker/.julia/v0.6/PyCall/src/exception.jl:56
[inlined]
 in pyerr_check at /home/nbecker/.julia/v0.6/PyCall/src/exception.jl:61
[inlined]
 in macro expansion at /home/nbecker/.julia/v0.6/PyCall/src/exception.jl:79
[inlined]
 in #_pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject,
::Array{Float64,1}, ::Vararg{Any,N}) at
/home/nbecker/.julia/v0.6/PyCall/src/PyCall.jl:546
 in _pycall(::PyCall.PyObject, ::Array{Float64,1}, ::Vararg{Any,N}) at
/home/nbecker/.julia/v0.6/PyCall/src/PyCall.jl:534
 in #pycall#70(::Array{Any,1}, ::Function, ::PyCall.PyObject,
::Type{PyCall.PyAny}, ::Array{Float64,1}, ::Vararg{Any,N}) at
/home/nbecker/.julia/v0.6/PyCall/src/PyCall.jl:568
 in pycall(::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Array{Float64,1},
::Vararg{Any,N}) at /home/nbecker/.julia/v0.6/PyCall/src/PyCall.jl:568
 in #plot#85(::Array{Any,1}, ::Function, ::Array{Float64,1},
::Vararg{Any,N}) at /home/nbecker/.julia/v0.6/PyPlot/src/PyPlot.jl:399
 in plot(::Array{Float64,1}, ::Vararg{Any,N}) at
/home/nbecker/.julia/v0.6/PyPlot/src/PyPlot.jl:396
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 in macro expansion at ./REPL.jl:97 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:66

julia>

**Comment by nbecker** [comment]
After trying to update various packages, now I get:

 plot(rand(10))
ERROR: PyCall.PyError(":PyObject_Call",PyCall.PyObject(Ptr{PyCall.PyObject_struct} @0x00007feda7d6d980),PyCall.PyObject(Ptr{PyCall.PyObject_struct} @0x00007fed923f5d58),PyCall.PyObject(Ptr{PyCall.PyObject_struct} @0x00007fed92401608))
Stacktrace:
 [1] pyerr_check at /home/nbecker/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
 [2] pyerr_check at /home/nbecker/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
 [3] macro expansion at /home/nbecker/.julia/v0.6/PyCall/src/exception.jl:79 [inlined]
 [4] #_pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /home/nbecker/.julia/v0.6/PyCall/src/PyCall.jl:546
 [5] _pycall(::PyCall.PyObject, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /home/nbecker/.julia/v0.6/PyCall/src/PyCall.jl:534
 [6] #pycall#70(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /home/nbecker/.julia/v0.6/PyCall/src/PyCall.jl:568
 [7] pycall(::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /home/nbecker/.julia/v0.6/PyCall/src/PyCall.jl:568
 [8] #plot#85(::Array{Any,1}, ::Function, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /home/nbecker/.julia/v0.6/PyPlot/src/PyPlot.jl:400
 [9] plot(::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /home/nbecker/.julia/v0.6/PyPlot/src/PyPlot.jl:397
 [10] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 [11] macro expansion at ./REPL.jl:97 [inlined]
 [12] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:66

**Comment by giordano** [comment]
@nbecker which version of matplotlib are you using?

**Comment by stevengj** [comment]
@nbecker, the `TypeError` seems to be a bug in Matplotlib's qt4agg backend when using the PyQt5 compatibility shims, but with the latest version of PyPlot and PyPlot you can just use the qt5agg backend.  It works with Julia 0.5.

With Julia 0.6, right now some of PyPlot's dependencies aren't working with 0.6 yet, so I can't really check whether PyPlot is working until those are fixed.

Closing this as the Qt issues encountered above should be fixed by using qt5agg.
