### ISSUE TITLE
Can't import scipy modules and have PyPlot build correctly: julia 0.5

### ISSUE THREAD

**Issue by bradleyashton** [JuliaPy/PyPlot.jl#267]
I do a .dmg install on macOS Sierra (have tried this also via homebrew, same issue)

then 

Pkg.add("PyCall")

I get an error telling me to rebuild with 

ENV["PYTHON"]=""
""
Pkg.build("PyCall")

which completes without error. Then

using PyCall

gives the following error when trying to import:

julia> @pyimport scipy.optimize as so
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named scipy.optimize',)

I tried rebuilding PyCall by pointing to python 3.5 which fixed the @pyimport issue. Then I have a broken build of PyPlot (even when rebuilding with specific environment for python2.7).

Any help would be gratefully received!

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

**Comment by stevengj** [comment]
If you use `ENV["PYTHON"]=""`, then it uses its own Miniconda distribution of Python rather than the system Python.  That distro doesn't install SciPy by default, so you have to install it by doing `using Conda; Conda.add("scipy")`.

**Comment by bradleyashton** [comment]
worked! I am slowly getting familiar with the package environment, thanks so much for dealing my novice question.
