### ISSUE TITLE
qt5 backend on Windows with anaconda is broken

### ISSUE THREAD

**Issue by Datseris** [JuliaPy/PyPlot.jl#278]
Windows user encountered the problem:
" This application failed to start because it could not find or load the Qt platform plugin "windows" in "" .
Reinstalling the application may fix this prolem. "

This problem arose after `Pkg.update()` of PyPlot to version 2.3.0. Before the update everything was working perfectly.

**Comment by stevengj** [comment]
What happens if you try (in a new session):
```
ENV["MPLBACKEND"]="qt4agg"
using PyPlot
```

**Comment by Datseris** [comment]
If I use this it works perfectly!

**Comment by stevengj** [comment]
Alternatively, can you try `using Conda; Conda.update()` to update Conda?

See also https://github.com/ContinuumIO/anaconda-issues/issues/1270

**Comment by Datseris** [comment]
When I typed `Conda.update()` it said that it is downloading miniconda so I immediately terminated execution. I have a python installation working.

**Comment by stevengj** [comment]
Try `Pkg.checkout("PyCall")` to see if the latest version fixes the problem (without having to set an environment var).

**Comment by Datseris** [comment]
Hi,I am sorry but it did not fix it. The error is exactly the same.

**Comment by stevengj** [comment]
M

**Comment by PaulSoderlind** [comment]
Same problem here. This makes PyPlot work on my Win7 (64, Julia 0.5.0) machine: 
ENV["MPLBACKEND"]="tk"

/Paul S

**Comment by stevengj** [comment]
Can someone check their `.matplotlibrc`?  Do:
```jl
using PyCall
PyDict(pyimport("matplotlib")["rcParams"])["backend"]
```
to see if you have a matplotlibrc file that specifies the broken backend.

Also, does it work with the Conda Python (`ENV["PYTHON"]=""; Pkg.build("PyCall")`)?

**Comment by PaulSoderlind** [comment]
```
using PyCall
PyDict(pyimport("matplotlib")["rcParams"])["backend"]
```
returns "Qt5Agg" on my Win7 (64, 0.5.0) machine with miniconda 3.5 installed.

/Paul S

**Comment by stevengj** [comment]
Does matplotlib work in Python?

**Comment by PaulSoderlind** [comment]
>Does matplotlib work in Python with this backend?
Yes, it seems so. I just tried a small example from the command line. No options, just plt.plot(x,y) and then plt.show(). Worked fine.
/Paul S

**Comment by stevengj** [comment]
Are you sure it's the same Python?  (`PyCall.python` will show which `python` it is using?)   Maybe it's some kind of weird path issue, where it's not looking in the right place?

**Comment by stevengj** [comment]
[Apparently](http://stackoverflow.com/questions/20495620/qt-5-1-1-application-failed-to-start-because-platform-plugin-windows-is-missi) there is some `QT_QPA_PLATFORM_PLUGIN_PATH` environment variable that tells Qt where to find plugins.  Can you check whether this is set in Python?

```py
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH']
```

**Comment by PaulSoderlind** [comment]
>(PyCall.python will show which python it is using?) 

gives "C:\\Miniconda3\\python.exe" (the same one as I used for testing plt.plot())

>os.environ['QT_QPA_PLATFORM_PLUGIN_PATH']

I am no python expert by any means, but this variable does not seem to be set. All I get is "...KeyError(key) from None"

**Comment by Datseris** [comment]
Hello, sorry for the late joining in the discussion.
For me
```
using PyCall
PyDict(pyimport("matplotlib")["rcParams"])["backend"]
``` 
returns  "Qt5Agg"  as well. I am using Anaconda for Python 2.7.

Plotting in Spyder (thus Python) works perfectly for me.

As expected, the 
```
import matplotlib.pyplot as plt
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH']
```
returns key error. This key does not exist in there.

**Comment by stevengj** [comment]
I've pushed a workaround (if matplotlibrc on windows specifies qt5agg, use qt4agg instead) for now.    Please do `Pkg.checkout("PyCall")` and try again to see if your problem is fixed.

These kinds of path issues are really frustrating... I've hit numerous cases where it seems like the `python` executable is doing some magic initialization that is not occurring if you just link `libpython` and initialize Python via the documented API.

@tkelman, could it be some kind of Windows "manifest" thing in which the conda `python` executable has some metadata that tells it where to look for the qt libraries?    (You can still force it to try the qt5agg backend by `ENV["MPLBACKEND"]="qt5agg"; using PyPlot` if you want to try it out.)

**Comment by tkelman** [comment]
I can't reproduce this.

**Comment by PaulSoderlind** [comment]
>do ```Pkg.checkout("PyCall")```

I should probably leave this to @Datseris but I still noticed the following (and it holds w/w.o. the new PyCall master):
if I just do
```
using PyPlot
figure()
```
then Julia (Win7, 64, 0.5.0) crashes (with a very quick error message).
This can be solved (on my machine) be either setting ENV["MPLBACKEND"]="tk" or by
```
using PyCall
pygui(:tk)
``` 
The crash is the "problem" for me. It started happening after PyPlot 2.3.0 was installed a few days ago.

Paul S

**Comment by Datseris** [comment]
Well after the update I did today, I got a completely different error. By the way, during my today update "Gkt" was downloaded and built for the first time ever...

ERROR MESSAGE:
```
INFO: Precompiling module PyPlot.
WARNING: Module BinDeps with uuid 44836290325184 is missing from the cache.
This may mean module BinDeps does not support precompilation but is imported by a module that does.
ERROR: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
 in require(::Symbol) at .\loading.jl:385
 in _include_from_serialized(::String) at .\loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:187
 in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:217
 in require(::Symbol) at .\loading.jl:371
 in include_from_node1(::String) at .\loading.jl:488
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\Users\migos\.julia\v0.5\PyPlot\src\PyPlot.jl, in expression starting on line 5
Failed to precompile PyPlot to C:\Users\migos\.julia\lib\v0.5\PyPlot.ji.
```

**Comment by Datseris** [comment]
Now not even `ENV["MPLBACKEND"]="qt4agg"` works

**Comment by stevengj** [comment]
@Datseris, I'm confused; qt4agg worked for you two days ago.

**Comment by Datseris** [comment]
I am quite as confused as I have done 0 changes in everything in my computers. The only thing I ever did was `Pkg.checkout("PyPlot")` and `Pkg.update()`. Tell me how I can help.

**Comment by Datseris** [comment]
PyPlot works now for me. This is so weird!!! (I am on master branch)

**Comment by stevengj** [comment]
What is `PyPlot.backend`?

**Comment by Datseris** [comment]
Right now, for me, it is `qt4agg`

**Comment by stevengj** [comment]
I tried on a Windows 8 machine, and qt4agg is not working for me either, so I changed it to ignore any qt backend in matplotlibrc and default to tkagg.  Try `Pkg.checkout`.

**Comment by Datseris** [comment]
I am not on PyPlot master yet it works for me right now! Sorry if I did not make it clear!

**Comment by Datseris** [comment]
Okay, now just to confirm everything, I am on PyPlot master by `checkout`, my backend is still `qt4agg` and everything is working perfectly.

**Comment by stevengj** [comment]
I was able to get the qt5agg backend working on Windows with Conda by setting:
```julia
ENV["QT_QPA_PLATFORM_PLUGIN_PATH"]=Pkg.dir("Conda","deps","usr","Library","plugins","platforms")
```
which is the location of the `qwindows.dll` file for Conda.   Not sure what the generic way to get this path is...

**Comment by stevengj** [comment]
Okay, the problem seems to be that the wrong paths are hard-coded into the Qt library.  If I do:
```jl
using PyCall
linfo = pyimport("PyQt5")["QtCore"]["QLibraryInfo"]
linfo["location"](linfo["PluginsPath"])
```
it prints (for Conda): `"C:/Users/ray/qtb-2.7-64/_b_env/Library/plugins"`, which apparently is the path on the machine of the developer ("ray") who built the Qt library that is shipped with Conda.

There is a `qt.conf` file in `Pkg.dir("Conda","deps","usr")` that has the the correct paths, but apparently this is being ignored?

**Comment by stevengj** [comment]
Aha, I think I've figured out why PyPlot fails and Python succeeds: as described in pyqt/python-qt5/issues#2, "The behaviour is that Qt looks for qt.conf in the same directory as the current executable."

This means that it works when running `python.exe` from the right directory, but not when running Julia.

**Comment by stevengj** [comment]
Okay, some more info: I think it uses the location of `sys.executable` to find `qt.conf`.   On most platforms, `sys.executable` corresponds to whatever we pass to `Py_SetProgramName` when we initialize libpython, and we pass the location of the `python` executable.  However, on Windows (of course) it is different, and `sys.executable` *ignores* `Py_SetProgramName` and [instead always uses the path of the running program, here julia.exe](https://github.com/python/cpython/blob/e0a10190f88e474a159da92b7b5be472e0d7f325/PC/getpathp.c#L430-L490).

**Comment by stevengj** [comment]
Hmm, worse than that: the location of `qt.conf` is determined by [Qt itself](http://doc.qt.io/qt-5/qt-conf.html), and it's not clear if we can override it. 😢

**Comment by tkelman** [comment]
Ray would be @mingwandroid

**Comment by stevengj** [comment]
I filed a Qt issue: https://bugreports.qt.io/browse/QTBUG-58637

**Comment by stevengj** [comment]
Should be fixed now with `Pkg.checkout("PyCall")`, which now sets the `QT_PLUGIN_PATH` environment variable by parsing `qt.conf`, and `qt5agg` seems to be working again on Windows.

I'll tag a new PyCall release soon.

**Comment by mingwandroid** [comment]
Can anyone give me step by step instructions to reproduce this? Please assume I have never used Julia before.

It seems to me like the conda Qt5 post install batch file hasn't been run here.

**Comment by stevengj** [comment]
@mingwandroid, the post-install batch file was run here, and `qt.conf` existed, but it is installed in the location of `python.exe`.  The problem is that we are not running `python.exe`, we are running `julia.exe`, and loading libpython dynamically in order to run matplotlib.   Because of that, Qt is looking in the wrong location for `qt.conf`, and hence is not finding it.  Currently, there seems to be no way to tell Qt to look in a different location for `qt.conf`, so I [filed a Qt issue](https://bugreports.qt.io/browse/QTBUG-58637).

So, I don't think the problem is the fault of Conda or Python.

We are now working around the issue by parsing `qt.conf` ourselves (looking for it in the path of `python.exe`) and using it to set the `QT_PLUGIN_PATH` environment variable, and this seems to work.  To reproduce the problem, therefore, you'd have to disable this workaround.  I would be happy to give you detailed instructions if you want.

**Comment by IljaK91** [comment]
I got this issue yesterday, setting "ENV["MPLBACKEND"]="qt4agg"" helps indeed.

**Comment by carlogalli** [comment]
Likewise, Qt5 still creating this problem in Julia and Windows (so perhaps fixqtpath not effective), setting "ENV["MPLBACKEND"]="qt4agg" however fixes it.

By the way, the error I get when using Qt5 is a R6034 runtime error, and it took me a looong while to link that error message to this issue: perhaps other people had the same problem.

**Comment by greenflash1357** [comment]
This issue does not seem to be resolved.

I am experiencing the same on Windows 10, Julia 0.6.1, with Qt5 (PyCall, PyPlot on master, Conda updated).

As above, `ENV["MPLBACKEND"] = "Qt4Agg"` resolves it.

**Comment by PaulSoderlind** [comment]
> This issue does not seem to be resolved

Well, I see something different. With Win 10, Julia 0.6.1 and Miniconda 3.6 (everything updated), 
`ENV["MPLBACKEND"]="qt5agg"`
seems to work fine.

**Comment by IljaK91** [comment]
I just tried what PaulSonderlind said. After removing Conda and installing it anew with Python version 3.6, I was able to run the following code without specifying a different backend.

```
Pkg.rm("Conda")
ENV["CONDA_JL_VERSION"]=3
Pkg.add("Conda")
Pkg.build("PyCall")
Pkg.add("PyPlot")
using PyPlot
figure()
x = collect(1:1:10)
y = rand(10,1)
plot(x,y)
```

Is there an issue with using Conda with Python version 2.7?

**Comment by mingwandroid** [comment]
I think the issue is likely to be either https://github.com/JuliaPy/PyPlot.jl/issues/278#issuecomment-277559770 or DLL hell on your own machine. I expect you may have a DLL called `windows.dll` somewhere on your PATH.

**Comment by yunhuihe** [comment]
Hi,
I have the same issue about Julia-PyPlot. I use stevengj 's suggestion: ENV["MPLBACKEND"] = "qt4agg". But  I must set this every time when I open a session. Is any way to fix this? Thanks!

**Comment by stevengj** [comment]
You can change the backend permanently by editing your `.matplotlibrc` file.
