### ISSUE TITLE
Broken on master due to display detection

### ISSUE THREAD

**Issue by yuyichao** [JuliaPy/PyPlot.jl#281]
PyPlot is currently broken for me on master in REPL due to https://github.com/JuliaLang/julia/pull/19993. The issue seems to be that `application/postscript` and `image/svg+xml` are `istextmime` so `displayable` of them returns true for the REPL (`TextDisplay`), triggering the logic to use the `Agg` backend instead of showing a window....

Removing the two problematic entries from `aggformats` locally fixes the issue (obviously not the right solution).

**Comment by stevengj** [comment]
I think it would be fine to just do `isdisplayok() = displayable(MIME("image/png"))`, on the theory that any real graphical display should at least support PNG.

**Comment by yuyichao** [comment]
That would certainly work for me. =)
