### ISSUE TITLE
trying to use pyplot

### ISSUE THREAD

**Issue by yaelvid** [JuliaPy/PyPlot.jl#282]
please help me, I want to use the pyplot, I tried to run the commend: "using PyPlot".
 in the picture attached is the problem. I tried every thing I could find, nothing helped me.

thanks in advanced
<img width="406" alt="aaaaa" src="https://cloud.githubusercontent.com/assets/24911621/23105883/6b8811e6-f6ee-11e6-8025-aaba591533a4.PNG">

**Comment by stevengj** [comment]
It works fine for me on Julia 0.5.  What is the output of `versioninfo(true)`?

**Comment by yaelvid** [comment]
<img width="400" alt="vkuthhhh" src="https://cloud.githubusercontent.com/assets/24911621/23215742/18615a60-f91c-11e6-9893-faf023731482.PNG">

**Comment by yaelvid** [comment]
<img width="392" alt="dddddddddcc" src="https://cloud.githubusercontent.com/assets/24911621/23215973/f00f2168-f91c-11e6-9877-feb76ff44ac4.PNG">

**Comment by stevengj** [comment]
Compat seems to be pinned at an old version.  Try `Pkg.free("Compat")` followed by `Pkg.update()` to go back to the latest Compat release.

**Comment by yaelvid** [comment]
it worked, Thank you!!
