### ISSUE TITLE
how to update matplotlib? 

### ISSUE THREAD

**Issue by floswald** [JuliaPy/PyPlot.jl#284]
Hi,

I installed matplotlib via `Conda.jl`, i.e. the route you recommend in the readme. I see in folder `/Users/florian.oswald/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/` 

```
matplotlib-1.5.1-py2.7.egg-info
matplotlib
```

hence i conclude that i have version 1.5 of matplotlib. is it possible to update this to a more recent version? I am having an [issue](https://github.com/JuliaPlots/Plots.jl/issues/715) on Plots.jl

thanks

**Comment by stevengj** [comment]
`using Conda; Conda.update()`
