### ISSUE TITLE
No working GUI backend found on OS X

### ISSUE THREAD

**Issue by crbinz** [JuliaPy/PyPlot.jl#288]
I had to wipe my ~/.julia/v0.5 directory because of the 'unsatisfiable package requirements' mess, and now I'm getting this error on macOS Sierra. XQuartz is installed. My `matplotlibrc` has: `backend : Qt4Agg` and `backend.qt4 : PyQt4`, which I believe has not changed since I had it working.

**Comment by stevengj** [comment]
You wiped your PyCall configuration, so now it is defaulting to Conda's Python; maybe it was using a system `python` before?   You can always do
```
ENV["PYTHON"]="python"
Pkg.build("PyCall")
```
to go back to the system Python.

**Comment by stevengj** [comment]
Or alternatively change `Qt4Agg` to `Qt5Agg`, since Qt4Agg started running into trouble with the Conda Python on MacOS some time ago (#164).

(Qt5Agg is now the default in PyPlot with MacOS, but your matplotlibrc is overriding that.)

**Comment by crbinz** [comment]
Changing to the system python fixes this. FWIW, changing `Qt4Agg` to `Qt5Agg` and using Conda's python gives me the same error, but I'll just use the system python.

**Comment by stevengj** [comment]
That's weird, Qt5Agg works fine for me with Conda on MacOS 10.11.6:
```
  | | |_| | | | (_| |  |  Version 0.5.1 (2017-03-05 13:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> using PyPlot

julia> PyPlot.backend
"Qt5Agg"

julia> plot(rand(100)) # plot window appears
```
