### ISSUE TITLE
No module named mpl_toolkits.mplot3d

### ISSUE THREAD

**Issue by MSICL** [JuliaPy/PyPlot.jl#294]
Hey, 

I have just updated my macOS to Sierra and now PyPlot is acting up.
Upon typing 'using PyPlot' I get an error 

```
ERROR: LoadError: InitError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named mpl_toolkits.mplot3d',)
[...]

```
I am using Julia Version 0.5.0, I already ran Pkg.update() without any errors. But starting Julia and running using PyPlot still gives the aforementioned error.

In addition, I tried:`using PyCall; @pyimport matplotlib.pyplot as plt;`
without any errors. In fact I can use `plt.contour(X,Y;Z) 
`to plot in Julia.
Another curiosity about this is the fact that running 'using PyPlot' a second time won't cause any errors and allows 3D plotting.

Running Pkg.checkout("PyPlot") gives:

```
INFO: Checking out PyPlot master...
INFO: Pulling PyPlot latest master...
WARNING: unknown DataFrames commit 84523937, metadata may be ahead of package cache
WARNING: julia is fixed at 0.5.0 conflicting with requirement for DataArrays: [0.6.0-,∞)
INFO: No packages to install, update or remove
```
Does anyone have an idea as to how to fix this? Drop me a line if you need more information. Thanks in advance!

**Comment by stevengj** [comment]
What is `using PyCall; PyCall.python`?

**Comment by MSICL** [comment]
Running this in the console gives

```
using PyCall; PyCall.python
"/usr/bin/python"
```

I hope that helps. Let me know if you need further information.

**Comment by stevengj** [comment]
A workaround would be to use the conda python: do `ENV["PYTHON"]=""; Pkg.build("PyCall")` (only needs to be done once, and it will remember in all future sessions).  This is nicer than using Apple's bundled `/usr/bin/python` anyway because then PyCall packages can auto-install dependencies.

**Comment by MSICL** [comment]
Marvellous, that really did the trick. PyPlot is working as usual. Thanks a ton!
