### ISSUE TITLE
scatter don't change color in the same figure

### ISSUE THREAD

**Issue by CaBeOli** [JuliaPy/PyPlot.jl#297]
I trying to use scatter inside a looping using the same figure, but different from using plot, scatter don't change the colors of the sequence plots. The problem is that the data become ambiguous. How can I chance the colours without using a different code for each plot?
I'm using the code: 
`for col in 2:2:32
  index = 31 
  figure(1)  
  plot(P_rel[2:index,col-1]*(2*π*(3.32/2)/30),P_rel[2:index,col]" )
  scatter(P_rel[2:index,col-1]*(2*π*(3.32/2)/30),P_rel[2:index,col])
end`

**Comment by stevengj** [comment]
This is really a Matplotlib issue.  See here for a solution: https://stackoverflow.com/questions/12236566/setting-different-color-for-each-series-in-scatter-plot-on-matplotlib
