### ISSUE TITLE
Defining styles such as pyplot.style.use('ggplot')

### ISSUE THREAD

**Issue by davidbp** [JuliaPy/PyPlot.jl#298]
Hello,

I would like to know if there is a way to define a style like you can do in python using  plt.style.use('ggplot').  Here there is an example: https://matplotlib.org/devdocs/gallery/style_sheets/ggplot.html

**Comment by stevengj** [comment]
Have you tried `plt[:style][:use]("ggplot")`?

**Comment by davidbp** [comment]
Thank you @stevengj , That just solve my problem. I could not find this instruction in the documentation. It looks like

>  plt.something.somethingelse

 is equivalent to

>  plt[:something][:somethingelse] 

isn't it?

**Comment by stevengj** [comment]
Yes, see [here](https://github.com/JuliaPy/PyPlot.jl#exported-functions) and [here](https://github.com/JuliaPy/PyCall.jl#pyobject).

**Comment by IlyaOrson** [comment]
It looks like this is no longer available?

```julia
import PyPlot as plt  #v2.10.0

# fails
plt.style.use("ggplot")

# works
plt.matplotlib.pyplot.style.use("ggplot")
```

**Comment by stevengj** [comment]
If you do `using PyPlot`, then `plt` is exported as a synonym for the `matplotlib.pyplot` module.    If you want to `import PyPlot as plt`, then you need `plt.plt`
