### ISSUE TITLE
Convert Colors.jl types to Python Tuples

### ISSUE THREAD

**Issue by gabrielgellner** [JuliaPy/PyPlot.jl#300]
I frequently like to use the sweetness of `Colors.jl` to set colors, but they don't seem compatible with sending to matplotlib. As I result I have the definition in my personal utilites:

```julia
function PyObject(t::Color)
    trgb = convert(RGB, t)
    ctup = map(float, (red(trgb), green(trgb), blue(trgb)))
    o = PyObject(ctup)
    return o
end
```

Would something like this makes sense in PyPlot?

**Comment by stevengj** [comment]
It would be "type piracy" in PyPlot, since PyPlot doesn't own either the Color type or the PyObject type.

**Comment by stevengj** [comment]
If `Color` were an iterable object (currently, it isn't), and PyPlot converted any iterable Julia object into an iterable Python object (currently, it doesn't), that would be sufficient, since I think Matplotlib allows any iterable object (e.g. tuples or arrays) for colors.

**Comment by stevengj** [comment]
PyCall could also include the conversion you mention above, but that would create a dependency on Colors, and would also entail a lossy conversion.

**Comment by gabrielgellner** [comment]
These are good points. I am always slow to understand type piracy ... but makes sense. I figured the dependency on Colors would be a no go for PyCall. Tricky decisions!

**Comment by gabrielgellner** [comment]
I will close this issue, as it now makes sense that this is not really a feature that can be added due to the way Julia packages are shipped. I will just continue to use my utils package. Thanks for explaining this.
