### ISSUE TITLE
How to change camera angle of 3D Plot using PyPlot in Julia?

### ISSUE THREAD

**Issue by jman87** [JuliaPy/PyPlot.jl#304]
I'm a fairly new Julia user and am coming from a MatLab/Octave background. In MatLab I had used the trimesh command to create some 3D plots so I have successfully converted my scripts over to Julia/PyPlot using the plot_trisurf command. However, after much searching, I have not found a way to put camera orientation statements in my script. I am needing to generate a number of figures and need to ensure they are all rotated the same way, which is not going to be the default. 

My typical script will look something like:

#code to calculate vectors xx, yy, and n
using PyPlot
plot_trisurf(xx,yy,n,cmap="rainbow")

I do also have some statements to set font sizes and axis labels but that's about it. Anybody got any ideas on how to set the camera view?

**Comment by stevengj** [comment]
There are [various examples of this online in the matplotlib docs](https://matplotlib.org/examples/mplot3d/rotate_axes3d_demo.html).  You use the [view_init](https://matplotlib.org/mpl_toolkits/mplot3d/api.html#mpl_toolkits.mplot3d.axes3d.Axes3D.view_init) function: For example:
```jl
surf(rand(20,20))
gca()[:view_init](30,7)
draw()
```

**Comment by photor** [comment]
> There are [various examples of this online in the matplotlib docs](https://matplotlib.org/examples/mplot3d/rotate_axes3d_demo.html). You use the [view_init](https://matplotlib.org/mpl_toolkits/mplot3d/api.html#mpl_toolkits.mplot3d.axes3d.Axes3D.view_init) function: For example:
> 
> ```julia
> surf(rand(20,20))
> gca()[:view_init](30,7)
> draw()
> ```

This one doesn't work in the new version. Does anybody have a new solution?
