### ISSUE TITLE
No working GUI backend found for matplotlib

### ISSUE THREAD

**Issue by davidzentlermunro** [JuliaPy/PyPlot.jl#307]
I encountered the following error and followed instructions on other threads to try:

`ENV["PYTHON"]=""; Pkg.build("PyCall")`

However, this starts an endless chain of julia downloading and installing miniconda: 

`INFO: Downloading miniconda installer ...
INFO: Installing miniconda ...
INFO: Downloading miniconda installer ...
INFO: Installing miniconda ...
INFO: Downloading miniconda installer ...
INFO: Installing miniconda ...
INFO: Downloading miniconda installer ...
INFO: Installing miniconda ...`

I am using julia 0.5.0 via Juno for JuliaPro0.50.5

**Comment by stevengj** [comment]
If you have a problem installing Miniconda, you should report an issue at Conda.jl.
