### ISSUE TITLE
Latex Font Not Adjusted

### ISSUE THREAD

**Issue by cortner** [JuliaPy/PyPlot.jl#309]
The following code 
```
using PyPlot, LaTeXStrings, PyCall
PyPlot.rc("font", family="serif", size=14)
fig = plot(rand(10))
xlabel(L"latex: $r [ \AA ]$")
```
produces a plot where all fonts are serif except the Latex text remains sans-serif.

This fixes it somewhat
```
using PyPlot, LaTeXStrings, PyCall
PyPlot.rc("font", family="serif", size=14)
rcParams = PyDict(PyPlot.matplotlib["rcParams"])
rcParams["text.usetex"] = true
fig = plot(rand(10))
xlabel(L"latex: $r [ \AA ]$")
```
but I think the font is still not consistent (though maybe one needs to fix the "serif" choice?) 

Either way, this seems to be an issue since matplotlib 2.0; probably these issues are related:
* https://github.com/matplotlib/matplotlib/issues/8317
* https://github.com/matplotlib/matplotlib/issues/8436

I am not entirely sure what the default behaviour ought to be but the current behaviour certainly seems  wrong. Maybe this will be fixed in a matplotlib update, so creating a work-around now might not be worthwhile, but I couldn't tell from those issues whether this was actually the case.

**Comment by stevengj** [comment]
This is probably a limitation of the [mathtext](https://matplotlib.org/users/mathtext.html#mathtext-tutorial) equation renderer?  In any case, it is a Matplotlib problem, not PyPlot.   Defaulting to `usetex = true` is not feasible because it would require everyone to have a working LaTeX installation.

**Comment by cortner** [comment]
would you be open to adding an easier path to setting `usetex`? E.g. 
```
PyPlot.usetex(tf) = PyDict(PyPlot.matplotlib["rcParams"])["text.usetex"] = tf
```

**Comment by stevengj** [comment]
How about just a global `PyPlot.rcParams` that is a PyDict?

**Comment by cortner** [comment]
Even better

**Comment by stevengj** [comment]
A PR to implement that would be welcome.

**Comment by cortner** [comment]
happy to, didn't take too long to do - only I had to learn more about matplotlib and now I realize that one can achieve the same with  `PyPlot.rc("text", usetex=true)`? Maybe not worth it then?

**Comment by stevengj** [comment]
Maybe not worth it...
