### ISSUE TITLE
plot_trisurf: color and facecolor keyword 

### ISSUE THREAD

**Issue by nlichtenberg** [JuliaPy/PyPlot.jl#323]
How do you set individual triangle colors when plotting with `plot_trisurf`?
So far, I am able to set individual edge colors by supplying an Nx3 array (N = number of triangles) or an N tuple of 3-tuples to the `edgecolor` keyword.
Using the `facecolor` keyword has no effect.
The `color` keyword can be supplied with a 3- or 4-tuple to apply a uniform coloring of the triangles.
(Also, `color` does not allow arrays, which seems inconsistent compared to edgecolor)

Here's my code:
```
using PyPlot
vert = [-1 0 0.5; 1 0.5 0; 0 1 1; 1 1 1]
tri = [1 2 3; 2 3 4]
edgec = [0. 0. 1.; 1. 0. 0.]        # works
edgec = ((0., 0., 1.),(1., 0., 0.)) # works

c    = (0.5, 0.5, 0.5)
#c = ((0., 0., 1.),(1., 0., 0.)) # Produces Invalid RGBA argument error when sent to "color"
#c = [1. 0. 0.] #  # Produces Invalid RGBA argument error when sent to "color"

# uniform color set by c:
p = plot_trisurf(vert[:,1],vert[:,2],vert[:,3],triangles=tri-1, color=c, edgecolor = edgec, shade=false, linewidth=10);

# here the faces get a blueish default color:
p = plot_trisurf(vert[:,1],vert[:,2],vert[:,3],triangles=tri-1, facecolor=edgec, edgecolor = edgec, shade=false, linewidth=10);

```

**Comment by stevengj** [comment]
Do you have something that works in Python?

**Comment by nlichtenberg** [comment]
No sorry, same for python. 
I moved my [question](https://github.com/matplotlib/matplotlib/issues/9535)
