### ISSUE TITLE
Error when `hatch` for `fill_between` is provided

### ISSUE THREAD

**Issue by mschauer** [JuliaPy/PyPlot.jl#333]
`fill_between(ts, upper, lower, hatch="X")` does not work. It gives `AttributeError: 'PyCall.jlwrap' object has no attribute 'count'`. But the argument `hatch = ` is accepted. (Edit: Double quotes)

**Comment by stevengj** [comment]
Strings in Julia use double quotes

**Comment by mschauer** [comment]
That is not the problem.

**Comment by mschauer** [comment]
I look into this. I had unsuccessfully tried *both* `fill_between(ts, upper, lower, hatch="X")` and `fill_between(ts, upper, lower, hatch='X')` and settled to report the wrong one (`?fill_between` uses Python strings which look like julica character constants). Anyway it turned out that this is a bug in Matplotlib or even higher upstream.
