### ISSUE TITLE
Error when using Gtk and PyPlot

### ISSUE THREAD

**Issue by LiftingBanana** [JuliaPy/PyPlot.jl#335]
Hey,
I guess this problem is related to https://github.com/JuliaPy/PyPlot.jl/issues/199 . 
When I try to use PyPlot and Gtk, I get errors all the time. I'm on MacOS10.13.1. At first I got a segmentation error, now after changing the backend as described in the post, the following code:
```
using PyPlot
using PyCall
using Gtk

figure()
```

produces the error: 

> (process:1214): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
2017-12-06 07:02:06.400 julia[1214:261660] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fbef5f626b0
2017-12-06 07:02:06.403 julia[1214:261660] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fbef5f626b0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff57dd92fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7e74bc76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff57e71da4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff57d4f670 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff57d4f038 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x00000001251a546f TkpInit + 383
	6   libtk8.6.dylib                      0x00000001250fe21e Initialize + 2622
	7   _tkinter.so                         0x0000000124f25be4 Tcl_AppInit + 84
	8   _tkinter.so                         0x0000000124f25448 Tkinter_Create + 1128
	9   libpython2.7.dylib                  0x0000000122f6e8f4 PyEval_EvalFrameEx + 22980
	10  libpython2.7.dylib                  0x0000000122f68cd4 PyEval_EvalCodeEx + 2164
	11  libpython2.7.dylib                  0x0000000122eeabb3 function_call + 355
	12  libpython2.7.dylib                  0x0000000122ec24d5 PyObject_Call + 101
	13  libpython2.7.dylib                  0x0000000122ed1642 instancemethod_call + 162
	14  libpython2.7.dylib                  0x0000000122ec24d5 PyObject_Call + 101
	15  libpython2.7.dylib                  0x0000000122f72a2f PyEval_CallObjectWithKeywords + 159
	16  libpython2.7.dylib                  0x0000000122ecf5d4 PyInstance_New + 148
	17  libpython2.7.dylib                  0x0000000122ec24d5 PyObject_Call + 101
	18  libpython2.7.dylib                  0x0000000122f6e578 PyEval_EvalFrameEx + 22088
	19  libpython2.7.dylib                  0x0000000122f68cd4 PyEval_EvalCodeEx + 2164
	20  libpython2.7.dylib                  0x0000000122f7301d fast_function + 109
	21  libpython2.7.dylib                  0x0000000122f6e399 PyEval_EvalFrameEx + 21609
	22  libpython2.7.dylib                  0x0000000122f68cd4 PyEval_EvalCodeEx + 2164
	23  libpython2.7.dylib                  0x0000000122eeabb3 function_call + 355
	24  libpython2.7.dylib                  0x0000000122ec24d5 PyObject_Call + 101
	25  libpython2.7.dylib                  0x0000000122f6f600 PyEval_EvalFrameEx + 26320
	26  libpython2.7.dylib                  0x0000000122f68cd4 PyEval_EvalCodeEx + 2164
	27  libpython2.7.dylib                  0x0000000122eeabb3 function_call + 355
	28  libpython2.7.dylib                  0x0000000122ec24d5 PyObject_Call + 101
	29  ???                                 0x0000000122a84dd2 0x0 + 4876422610
	30  ???                                 0x0000000122a82bb2 0x0 + 4876413874
	31  ???                                 0x0000000122a827a9 0x0 + 4876412841
	32  ???                                 0x0000000122a8262f 0x0 + 4876412463
	33  libjulia.0.6.1.dylib                0x000000010ab870e8 do_call + 200
	34  libjulia.0.6.1.dylib                0x000000010ab85216 eval + 870
	35  libjulia.0.6.1.dylib                0x000000010ab84ea1 jl_interpret_toplevel_expr + 49
	36  libjulia.0.6.1.dylib                0x000000010ab9b355 jl_toplevel_eval_flex + 1845
	37  libjulia.0.6.1.dylib                0x000000010ab9b10d jl_toplevel_eval_flex + 1261
	38  libjulia.0.6.1.dylib                0x000000010ab7f7cb jl_toplevel_eval_in + 523
	39  sys.dylib                           0x000000010cde0c9a julia_eval_18069 + 10
	40  sys.dylib                           0x000000010cde0cb0 jlcall_eval_18068 + 16
	41  sys.dylib                           0x000000010ce32304 julia_process_options_18952 + 1316
	42  sys.dylib                           0x000000010ce34c01 julia__start_18945 + 1201
	43  sys.dylib                           0x000000010ce35699 jlcall__start_18944 + 9
	44  julia                               0x000000010ab5e414 true_main + 1364
	45  julia                               0x000000010ab5de83 main + 227
	46  libdyld.dylib                       0x00007fff7f33a145 start + 1
	47  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
signal (6): Abort trap: 6
while loading no file, in expression starting on line 0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 5617399 (Pool: 5615968; Big: 1431); GC: 11

of which I don't understand a word. I also couldn't fix the "Locale not supported by C" warning.
Does anyone have a solution for this?

**Comment by stevengj** [comment]
The locale thing is just a harmless warning.  The real error is `unrecognized selector sent to instance` and indicates a problem in the backend … use a different backend.
