### ISSUE TITLE
WARNING: No working GUI backend found for matplotlib

### ISSUE THREAD

**Issue by MMalakhov** [JuliaPy/PyPlot.jl#336]
I'm trying to use PyPlot, but thats not effective. Problem is that I don't understand what it says to do, I'm not very good in programming. What the hell is Conda and Anaconda, how I should find them on my computer and what should I  type instead PKG in `pyimport_conda("matplotlib.pyplot", PKG)` so I can start work plotting.
I also tried 
ENV["PYTHON"]=""
Pkg.build("PyCall")
but it doesn't help.

I'm using Linux mint, I also installed Python and matplotlib packages.

Error log:

julia> using PyPlot
sys:1: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to u'Qt5Agg' by the following code:
  File "/home/malakhov/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()

WARNING: No working GUI backend found for matplotlib
ERROR: InitError: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)

The Python package matplotlib.pyplot could not be found by pyimport. Usually this means
that you did not install matplotlib.pyplot in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the matplotlib.pyplot module, you can
use `pyimport_conda("matplotlib.pyplot", PKG)`, where PKG is the Anaconda
package the contains the module matplotlib.pyplot, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.

) <type 'exceptions.ImportError'>
ImportError("/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/malakhov/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/../../.././libpng16.so.16)",)
  File "/home/malakhov/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/home/malakhov/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/home/malakhov/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/contour.py", line 21, in <module>
    import matplotlib.font_manager as font_manager
  File "/home/malakhov/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/font_manager.py", line 58, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir

Stacktrace:
 [1] pyerr_check at /home/malakhov/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
 [2] pyerr_check at /home/malakhov/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
 [3] macro expansion at /home/malakhov/.julia/v0.6/PyCall/src/exception.jl:81 [inlined]
 [4] pyimport(::String) at /home/malakhov/.julia/v0.6/PyCall/src/PyCall.jl:374
 [5] __init__() at /home/malakhov/.julia/v0.6/PyPlot/src/init.jl:184
 [6] _include_from_serialized(::String) at ./loading.jl:157
 [7] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [8] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:236
 [9] _require(::Symbol) at ./loading.jl:441
 [10] require(::Symbol) at ./loading.jl:405
during initialization of module PyPlot

**Comment by bisraelsen** [comment]
Getting the same problem using a fresh install of xubuntu 16.04. Any progress?

**Comment by raminammour** [comment]
Look at
https://github.com/JuliaPy/PyPlot.jl/issues/151
and fixes there, especially with `LD_PRELOAD=$PATH_TO_ZLIB/libz.so julia`

**Comment by MMalakhov** [comment]
I could fix it finally, but I'm not sure, what of this steps were really necessary and may be I forgot something:

At first I checked my Python distro in terminal:
```
 $ python
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

then I imported matplotlib to it:
`>>> import matplotlib.pyplot`
It was a problem, that I didn't had one tiny package, that I had to install in package manager. After this import I went to Julia command line and typed:

```
ENV["PYTHON"]="python"
Pkg.build("PyCall")

```

and only after that I could run `using PyPlot` without errors. 

May be I did other important steps before it, I tried a lot of solutions, but I hope it helpes.

**Comment by pierre-haessig** [comment]
I also got hit by this `WARNING: No working GUI backend found for matplotlib` since updgrading to julia 0.6. This warning  is in fact misleading since the underlying issue is the complete failure to load `PyPlot`. The problem lies with `ZLIB` as written (although a bit hidden) in the error message. Thanks @raminammour for pointing us to #151.

I believe this issue should be closed as duplicate.

**Comment by stevengj** [comment]
Closing as dup.
