### ISSUE TITLE
Verifying transaction failed

### ISSUE THREAD

**Issue by DeniOliveira** [JuliaPy/PyPlot.jl#339]
Hi guys,

i already installed pyplot, build pycall even conda. When i try to execute the following code:

`ENV["PYTHON"]="" #i dunno if this line is required
using PyPlot
x = linspace(0,2*pi,1000); y = sin.(3 * x + 4 * cos.(2 * x));
plot(x, y, color="red", linewidth=2.0, linestyle="--")
title("A sinusoidally modulated sinusoid")
show()`

i receive the following message: (almost a mom's letter hahahahaha)

--------------------------------------------------------------------

INFO: Installing matplotlib via the Conda matplotlib package...

Solving environment: done

## Package Plan ##

  environment location: /home/valdenir/.julia/v0.6/Conda/deps/usr

  added / updated specs:

    - matplotlib

The following NEW packages will be INSTALLED:

    backports:                     1.0-py27h63c9359_1   

    backports.functools_lru_cache: 1.4-py27he8db605_1   

    backports_abc:                 0.5-py27h7b3c97b_0   

    cycler:                        0.10.0-py27hc7354d3_0

    dbus:                          1.10.22-h3b5a359_0   

    expat:                         2.2.5-he0dffb1_0     

    fontconfig:                    2.12.4-h88586e7_1   

    freetype:                      2.8-hab7d2ae_1       

    functools32:                   3.2.3.2-py27h4ead58f_1

    glib:                          2.53.6-h5d9569c_2   

    gst-plugins-base:              1.12.2-he3457e5_0   

    gstreamer:                     1.12.2-h4f93127_0   

    icu:                           58.2-h9c2bf20_1     

    jpeg:                          9b-h024ee3a_2       

    libpng:                        1.6.32-hbd3595f_4   

    libxcb:                        1.12-hcd93eb1_4     

    libxml2:                       2.9.4-h2e8b1d7_6     

    matplotlib:                    2.1.1-py27h0128e01_0 

    pcre:                          8.41-hc27e229_1     

    pyparsing:                     2.2.0-py27hf1513f8_1 

    pyqt:                          5.6.0-py27h4b1e83c_5 

    python-dateutil:               2.6.1-py27h4ca5741_1 

    pytz:                          2017.3-py27h001bace_0

    qt:                            5.6.2-h974d657_12   

    singledispatch:                3.4.0.3-py27h9bcb476_0

    sip:                           4.18.1-py27he9ba0ab_2

    ssl_match_hostname:            3.5.0.1-py27h4ec10b9_2

    subprocess32:                  3.2.7-py27h373dbce_0 

    tornado:                       4.5.2-py27h97b179f_0 

    xz:                            5.2.3-h55aa19d_2     

Preparing transaction: done

Verifying transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/exceptions.py", line 724, in __call__

        return func(*args, **kwargs)

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main.py", line 78, in _main

        exit_code = do_call(args, p)

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 76, in do_call

        exit_code = getattr(module, func_name)(args, parser)

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main_install.py", line 11, in execute

        install(args, parser, 'install')

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/install.py", line 255, in install

        handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/install.py", line 285, in handle_txn

        unlink_link_transaction.execute()

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/core/link.py", line 220, in execute

        self.verify()

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/common/io.py", line 415, in decorated

        return f(*args, **kwds)

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/core/link.py", line 207, in verify

        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/core/link.py", line 460, in _verify

        cls._verify_transaction_level(prefix_setups),

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/core/link.py", line 455, in <genexpr>

        exceptions = tuple(exc for exc in concatv(

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/core/link.py", line 323, in _verify_individual_level

        error_result = axn.verify()

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/core/path_actions.py", line 312, in verify

        source_sha256 = compute_sha256sum(self.source_full_path)

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 75, in compute_sha256sum

        return _digest_path('sha256', file_full_path)

      File "/home/valdenir/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 65, in _digest_path

        for chunk in iter(partial(fh.read, 8192), b''):

    IOError: [Errno 5] Input/output error

`$ /home/valdenir/.julia/v0.6/Conda/deps/usr/bin/conda install -y matplotlib`

  environment variables:

                 CIO_TEST=<not set>

                  CONDARC=/home/valdenir/.julia/v0.6/Conda/deps/usr/condarc-julia.yml

        CONDA_DEFAULT_ENV=/home/valdenir/.julia/v0.6/Conda/deps/usr

             CONDA_PREFIX=/home/valdenir/.julia/v0.6/Conda/deps/usr

               CONDA_ROOT=/home/valdenir/.julia/v0.6/Conda/deps/usr

            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path

           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path

                     PATH=/home/valdenir/bin:/home/valdenir/.local/bin:/usr/local/sbin:/usr/loca

                          l/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/

                          bin

       REQUESTS_CA_BUNDLE=<not set>

            SSL_CERT_FILE=<not set>

            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0

         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : base

    active env location : /home/valdenir/.julia/v0.6/Conda/deps/usr

       user config file : /home/valdenir/.condarc

 populated config files : /home/valdenir/.julia/v0.6/Conda/deps/usr/condarc-julia.yml

          conda version : 4.4.6

    conda-build version : not installed

         python version : 2.7.14.final.0

       base environment : /home/valdenir/.julia/v0.6/Conda/deps/usr  (writable)

           channel URLs : https://repo.continuum.io/pkgs/main/linux-64

                          https://repo.continuum.io/pkgs/main/noarch

                          https://repo.continuum.io/pkgs/free/linux-64

                          https://repo.continuum.io/pkgs/free/noarch

                          https://repo.continuum.io/pkgs/r/linux-64

                          https://repo.continuum.io/pkgs/r/noarch

                          https://repo.continuum.io/pkgs/pro/linux-64

                          https://repo.continuum.io/pkgs/pro/noarch

          package cache : /home/valdenir/.julia/v0.6/Conda/deps/usr/pkgs

                          /home/valdenir/.conda/pkgs

       envs directories : /home/valdenir/.julia/v0.6/Conda/deps/usr/envs

                          /home/valdenir/.conda/envs

               platform : linux-64

             user-agent : conda/4.4.6 requests/2.18.4 CPython/2.7.14 Linux/4.10.0-42-generic ubuntu/16.04 glibc/2.23

                UID:GID : 1000:1000

             netrc file : None

           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Upload successful.

ERROR: InitError: failed process: Process(setenv(`/home/valdenir/.julia/v0.6/Conda/deps/usr/bin/conda install -y matplotlib`,String["PATH=/home/valdenir/bin:/home/valdenir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", "DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path", "QT_ACCESSIBILITY=1", "UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/1965", "UPSTART_JOB=unity-settings-daemon", "DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-6zcOGeanqM", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_DESKTOP=ubuntu", "XDG_SESSION_TYPE=x11", "USER=valdenir", "XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg", "QT_IM_MODULE=ibus", "LESSCLOSE=/usr/bin/lesspipe %s %s", "SESSIONTYPE=gnome-session", "INSTANCE=Unity", "GDMSESSION=ubuntu", "CLUTTER_IM_MODULE=xim", "XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop", "LESSOPEN=| /usr/bin/lesspipe %s", "SHELL=/bin/bash", "XDG_SEAT=seat0", "XAUTHORITY=/home/valdenir/.Xauthority", "CONDARC=/home/valdenir/.julia/v0.6/Conda/deps/usr/condarc-julia.yml", "GTK_MODULES=gail:atk-bridge:unity-gtk-module", "GNOME_KEYRING_PID=", "GTK_IM_MODULE=ibus", "QT_QPA_PLATFORMTHEME=appmenu-qt5", "XMODIFIERS=@im=ibus", "TERM=xterm-256color", "HOME=/home/valdenir", "VTE_VERSION=4205", "GTK2_MODULES=overlay-scrollbar", "IM_CONFIG_PHASE=1", "COMPIZ_CONFIG_PROFILE=ubuntu", "UPSTART_INSTANCE=", "XDG_CURRENT_DESKTOP=Unity", "LANG=pt_BR.UTF-8", "SHLVL=1", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "LOGNAME=valdenir", "XDG_RUNTIME_DIR=/run/user/1000", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "DESKTOP_SESSION=ubuntu", "GDM_LANG=pt_BR", "OLDPWD=/home/valdenir", "_=/usr/local/bin/julia", "CONDA_DEFAULT_ENV=/home/valdenir/.julia/v0.6/Conda/deps/usr", "GPG_AGENT_INFO=/home/valdenir/.gnupg/S.gpg-agent:0:1", "PWD=/home/valdenir/Documentos/programas/Julia", "DISPLAY=:0", "UPSTART_EVENTS=started starting", "LANGUAGE=pt_BR:pt:en", "XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/valdenir", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0", "XDG_VTNR=7", "WINDOWID=81788938", "MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path", "XDG_SESSION_ID=c2", "CONDA_PREFIX=/home/valdenir/.julia/v0.6/Conda/deps/usr", "QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1", "QT4_IM_MODULE=xim", "LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:", "GNOME_KEYRING_CONTROL=", "JOB=gnome-session", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]

Stacktrace:

 [1] pipeline_error(::Base.Process) at ./process.jl:682

 [2] run(::Cmd) at ./process.jl:651

 [3] add(::String, ::String) at /home/valdenir/.julia/v0.6/Conda/src/Conda.jl:203

 [4] pyimport_conda(::String, ::String, ::String) at /home/valdenir/.julia/v0.6/PyCall/src/PyCall.jl:586

 [5] __init__() at /home/valdenir/.julia/v0.6/PyPlot/src/init.jl:172

 [6] _include_from_serialized(::String) at ./loading.jl:157

 [7] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200

 [8] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:236

 [9] _require(::Symbol) at ./loading.jl:441

 [10] require(::Symbol) at ./loading.jl:405

during initialization of module PyPlot

----------------------------------------------------------------------------------------------
it seems that everything will be fine and...Verifying transaction failed...What can i do?

Thanks everyone

**Comment by stevengj** [comment]
Sounds like a problem with Conda, not PyPlot.  Do
```
using Conda
Conda.add("matplotlib")
```
 and see if the problem occurs with Conda alone.
