### ISSUE TITLE
PyPlot crashes when Gadfly is in same workspace

### ISSUE THREAD

**Issue by daniellivingston** [JuliaPy/PyPlot.jl#346]
Steps to reproduce are below:

               _
	   _       _ _(_)_     |  A fresh approach to technical computing
	  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
	   _ _   _| |_  __ _   |  Type "?help" for help.
	  | | | | | | |/ _` |  |
	  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
	 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
	|__/                   |  x86_64-apple-darwin13.4.0

	julia> import Gadfly
	WARNING: Method definition midpoints(Base.Range{T} where T) in module Base at deprecated.jl:56 overwritten in module StatsBase at /Users/livingston/.julia/v0.6/StatsBase/src/hist.jl:535.
	WARNING: Method definition midpoints(AbstractArray{T, 1} where T) in module Base at deprecated.jl:56 overwritten in module StatsBase at /Users/livingston/.julia/v0.6/StatsBase/src/hist.jl:533.

	julia> import PyPlot

	julia> PyPlot.figure()
	2018-02-27 17:15:35.229 julia[32851:1569035] -[__NSCFType symbolicTraits]: unrecognized selector sent to instance 0x7fa0eb7d5f70
	2018-02-27 17:15:35.231 julia[32851:1569035] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFType symbolicTraits]: unrecognized selector sent to instance 0x7fa0eb7d5f70'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x00007fffccc362cb __exceptionPreprocess + 171
		1   libobjc.A.dylib                     0x00007fffe1a4d48d objc_exception_throw + 48
		2   CoreFoundation                      0x00007fffcccb7f04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
		3   CoreFoundation                      0x00007fffccba8755 ___forwarding___ + 1061
		4   CoreFoundation                      0x00007fffccba82a8 _CF_forwarding_prep_0 + 120
		5   AppKit                              0x00007fffca842daf -[NSFontManager traitsOfFont:] + 37
		6   libtk8.6.dylib                      0x0000000127ee2083 TkpFontPkgInit + 243
		7   libtk8.6.dylib                      0x0000000127e3a932 TkCreateMainWindow + 194
		8   libtk8.6.dylib                      0x0000000127e45ec6 CreateFrame + 758
		9   libtk8.6.dylib                      0x0000000127e464a7 TkListCreateFrame + 151
		10  libtk8.6.dylib                      0x0000000127e3e049 Initialize + 2153
		11  _tkinter.so                         0x0000000127c65be4 Tcl_AppInit + 84
		12  _tkinter.so                         0x0000000127c65448 Tkinter_Create + 1128
		13  libpython2.7.dylib                  0x0000000125ebf8f4 PyEval_EvalFrameEx + 22980
		14  libpython2.7.dylib                  0x0000000125eb9cd4 PyEval_EvalCodeEx + 2164
		15  libpython2.7.dylib                  0x0000000125e3bbb3 function_call + 355
		16  libpython2.7.dylib                  0x0000000125e134d5 PyObject_Call + 101
		17  libpython2.7.dylib                  0x0000000125e22642 instancemethod_call + 162
		18  libpython2.7.dylib                  0x0000000125e134d5 PyObject_Call + 101
		19  libpython2.7.dylib                  0x0000000125ec3a2f PyEval_CallObjectWithKeywords + 159
		20  libpython2.7.dylib                  0x0000000125e205d4 PyInstance_New + 148
		21  libpython2.7.dylib                  0x0000000125e134d5 PyObject_Call + 101
		22  libpython2.7.dylib                  0x0000000125ebf578 PyEval_EvalFrameEx + 22088
		23  libpython2.7.dylib                  0x0000000125eb9cd4 PyEval_EvalCodeEx + 2164
		24  libpython2.7.dylib                  0x0000000125ec401d fast_function + 109
		25  libpython2.7.dylib                  0x0000000125ebf399 PyEval_EvalFrameEx + 21609
		26  libpython2.7.dylib                  0x0000000125eb9cd4 PyEval_EvalCodeEx + 2164
		27  libpython2.7.dylib                  0x0000000125e3bbb3 function_call + 355
		28  libpython2.7.dylib                  0x0000000125e134d5 PyObject_Call + 101
		29  libpython2.7.dylib                  0x0000000125ec0600 PyEval_EvalFrameEx + 26320
		30  libpython2.7.dylib                  0x0000000125eb9cd4 PyEval_EvalCodeEx + 2164
		31  libpython2.7.dylib                  0x0000000125e3bbb3 function_call + 355
		32  libpython2.7.dylib                  0x0000000125e134d5 PyObject_Call + 101
		33  ???                                 0x000000011bfa50b0 0x0 + 4764356784
		34  ???                                 0x000000011bfa4ad2 0x0 + 4764355282
		35  ???                                 0x000000011bfae643 0x0 + 4764395075
		36  ???                                 0x000000011bfae4df 0x0 + 4764394719
		37  libjulia.0.6.0.dylib                0x0000000104460ab8 do_call + 200
		38  libjulia.0.6.0.dylib                0x000000010445eb12 eval + 882
		39  libjulia.0.6.0.dylib                0x000000010445e791 jl_interpret_toplevel_expr + 49
		40  libjulia.0.6.0.dylib                0x0000000104474a16 jl_toplevel_eval_flex + 1862
		41  libjulia.0.6.0.dylib                0x000000010445909b jl_toplevel_eval_in + 523
		42  sys.dylib                           0x00000001087022da julia_eval_17977 + 10
		43  sys.dylib                           0x00000001087022f0 jlcall_eval_17976 + 16
		44  sys.dylib                           0x0000000108774ba2 julia_eval_user_input_20273 + 594
		45  sys.dylib                           0x0000000108774dc0 jlcall_eval_user_input_20272 + 16
		46  ???                                 0x000000011bf589f0 0x0 + 4764043760
		47  ???                                 0x000000011bf58c80 0x0 + 4764044416
		48  libjulia.0.6.0.dylib                0x0000000104464f3c start_task + 364
	)
	libc++abi.dylib: terminating with uncaught exception of type NSException

	signal (6): Abort trap: 6
	while loading no file, in expression starting on line 0
	__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
	Allocations: 9885190 (Pool: 9883324; Big: 1866); GC: 19
	[1]    32851 abort      julia

I am running Gadfly 0.6.5 and PyPlot 2.3.2 on Julia 0.6.0 (macOS Sierra).

**Comment by montyvesselinov** [comment]
It works if you import PyPlot first.

**Comment by daniellivingston** [comment]
Checked and it does. Thanks! Closing issue.

**Comment by montyvesselinov** [comment]
It is a still a PyPlot bug that needs to be resolved.

-monty

On Thu, Mar 22, 2018 at 2:50 PM, Daniel Livingston <notifications@github.com

**Comment by montyvesselinov** [comment]
I will keep it open.

-monty
