### ISSUE TITLE
windows 10 install seems fine, but I get an InitError on using PyPlot

### ISSUE THREAD

**Issue by jeffersonroy** [JuliaPy/PyPlot.jl#347]
Hi,

I have been trying to install PyPlot after having to do a clean windows install.  I did the following, which has worked on multiple Windows machines including this one:

Pkg.add("PyCall")
ENV["PYTHON"]=""
Pkg.build("PyCall")
Pkg.add("PyPlot")

This all works without errors, but when I do:
julia> using PyPlot
ERROR: InitError: MethodError: no method matching lowercase(::Void)
Closest candidates are:
  lowercase(::Char) at strings/utf8proc.jl:200
  lowercase(::AbstractString) at strings/basic.jl:415
Stacktrace:
 [1] find_backend(::PyCall.PyObject) at C:\Users\JRoy\.julia\v0.6\PyPlot\src\init.jl:83
 [2] __init__() at C:\Users\JRoy\.julia\v0.6\PyPlot\src\init.jl:179
 [3] _include_from_serialized(::String) at .\loading.jl:157
 [4] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:200
 [5] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:236
 [6] _require(::Symbol) at .\loading.jl:441
 [7] require(::Symbol) at .\loading.jl:405
during initialization of module PyPlot

I tried matplotlib.pyplot in the pycall installed python, it works.

I have uninstalled Julia, cleared the folders, and retried, but that didn't help.

More info
Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

julia> using PyCall; PyCall.python
"C:\\Users\\JRoy\\.julia\\v0.6\\Conda\\deps\\usr\\python.exe"

Any guidance would be helpful.

Thank you,
-Jefferson

**Comment by stevengj** [comment]
Can you try `Pkg.checkout("PyPlot")` to try with the latest version?   (If the error still occurs, let me know what the new line number is in `PyPlot\src\init.jl`.)

**Comment by jeffersonroy** [comment]
Hi,
Thanks for the quick reply.  I did Pkg.checkout("PyPlot") here is the result:
julia> Pkg.checkout("PyPlot")
INFO: Checking out PyPlot master...
INFO: Pulling PyPlot latest master...
INFO: No packages to install, update or remove

julia> using PyPlot
ERROR: InitError: MethodError: no method matching lowercase(::Void)
Closest candidates are:
  lowercase(::Char) at strings/utf8proc.jl:200
  lowercase(::AbstractString) at strings/basic.jl:415
Stacktrace:
 [1] find_backend(::PyCall.PyObject) at C:\Users\JRoy\.julia\v0.6\PyPlot\src\init.jl:80
 [2] __init__() at C:\Users\JRoy\.julia\v0.6\PyPlot\src\init.jl:187
 [3] _include_from_serialized(::String) at .\loading.jl:157
 [4] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:200
 [5] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:236
 [6] _require(::Symbol) at .\loading.jl:441
 [7] require(::Symbol) at .\loading.jl:405
during initialization of module PyPlot

I also tried closing and restarting Julia after the Pkg.checkout.

-Jefferson

**Comment by stevengj** [comment]
Try
```jl
using PyCall
rcParams = PyDict(pyimport("matplotlib")["rcParams"])
rcParams["backend.qt4"]
```
It looks like that is returning `nothing`?  i.e. the `"backend.qt4"` key in your matplotlibrc file is set to `None`?    I didn't realize that this was a valid value for the backend parameter...

**Comment by jeffersonroy** [comment]
Hi
The plot thickens.  I have been including ENV["MPLBACKEND"]="qt4agg" in my .juliarc.jl file to stop runtime errors when plotting.  If I remove this a do using PyPlot I don't get errors.   With a plot(rand(10)), I do get a visual c++ runtime library error R6034.  I have visual c++ 2008 installed.  I have 2013 on my desktop.  Could this be the issue?
-Jefferson

**Comment by stevengj** [comment]
You didn't answer my question — is `rcParams["backend.qt4"]` returning `nothing`?

If so, I'm guessing you have a `backend.qt4 = None` line in your matplotlibrc file, which you could remove to eliminate the error?

> visual c++ runtime library error R6034

This probably indicates a conflict between the the MS C runtime used by Julia and by one of the Python dependencies.  (In the past, when I encountered this error, @tkelman fixed it by adding a manifest file to Julia JuliaPy/PyCall.jl#87.)   What is `PyPlot.backend` when you encounter this error?

**Comment by stevengj** [comment]
(I just pushed a patch that will allow `None` entries in the matplotlibrc file.  Use `Pkg.checkout` to get it.)

**Comment by jeffersonroy** [comment]
Sorry for not answering, you were correct that rcParams["backend.qt4"] returned nothing.  I applied the patch and it still returns nothing

julia> rcParams["backend.qt4"]

julia>

But it all works!  

I left the ENV["MPLBACKEND"]="qt4agg" in my .juliarc.jl

Thank you for the fix, all of your time today, and for PyPlot.jl! 

-Jefferson

**Comment by stevengj** [comment]
Yes, the patch treats a `None` entry as if the entry weren't there.  Glad that it is working now!
