### ISSUE TITLE
projection="3d"

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaPy/PyPlot.jl#351]
does not seem to work after the latest update (to 2.5.0), on Julia 0.6.2, Win 64, with local matplotlib 2.1.2.

Running
```
using PyPlot
figure()
subplot(111,projection="3d")
```
gives an error message which starts with
```
ERROR: LoadError: PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, kw)) <class 'ValueError'>
ValueError("Unknown projection '3d'",)
  File "C:\Miniconda3\lib\site-packages\matplotlib\pyplot.py", line 1050, in subplot
    a = fig.add_subplot(*args, **kwargs)
```

(Also the old syntax, `fig[:add_subplot](111, projection = "3d")` fails.

**Comment by stevengj** [comment]
mplot3d is now not loaded until you call one of the 3d plotting functions like `plot3D` (mainly to make PyPlot work on systems where mplot3d is not installed).

I'm afraid it didn't occur to me that people would be calling `subplot(111,projection="3d")` manually.   Why do you need this?    Can't you just call `plot3D` or `plot_surface` or similar directly without calling `subplot` with the `projection="3d"` argument?

As a workaround, you can manually load `mplot3d` by doing `PyPlot.PyObject(PyPlot.axes3D)`.

**Comment by stevengj** [comment]
That being said, we should probably manually overload `subplot` to load mplot3d if a `projection="3d"` argument is passed.  A PR for this would be welcome.

**Comment by PaulSoderlind** [comment]
>calling subplot(111,projection="3d") manually. 

Not really, but I sometimes do `subplot(221,projection="3d") `, or rather `fig[:add_subplot](221, projection="3d"`)` when I want one of the subplots to be a surface plot (and another being eg. a contour plot). Is there another way?

**Comment by stevengj** [comment]
Yes, manually call `PyPlot.PyObject(PyPlot.axes3D)` as I mentioned above, or equivalently `PyPlot.pyimport("mpl_toolkits.mplot3d.axes3d")`

**Comment by stevengj** [comment]
I added a function `using3D()` to explicitly load mplot3d in cases like this, and documented it in the README.
