### ISSUE TITLE
Plot not appearing when called from script

### ISSUE THREAD

**Issue by stumarcus576** [JuliaPy/PyPlot.jl#354]
The following test code works from the julia command window making a plot window, but not by running: julia myscript.jl from a terminal window. The latter does not generate a plot window.

using PyPlot
x = linspace(0,2*pi,1000); y = sin.(3 * x + 4 * cos.(2 * x));
plot(x, y, color="red", linewidth=2.0, linestyle="--")
title("A sinusoidally modulated sinusoid")

**Comment by stevengj** [comment]
You need to call `show()` in non-interactive mode: https://github.com/JuliaPy/PyPlot.jl#non-interactive-plotting
