### ISSUE TITLE
Event handler for interactive plot

### ISSUE THREAD

**Issue by KentaroTakeda** [JuliaPy/PyPlot.jl#356]
Hi,
I have the following julia code to work the function reset_(event) when somewhere is pressed.
How should I write to make a working the function only when the button is pressed?

`using PyCall`
`using PyPlot`

`const Button = matplotlib[:widgets][:Button]`

`axcolor = "lightgoldenrodyellow"`
`resetax = axes([0.8,0.025,0.1,0.04])`
`button = Button(resetax,"Reset",color=axcolor,hovercolor="0.925")`

`function reset_(event)`
`println("pressed reset button.")`
`end`
`connect("button_press_event", reset_)`

`figure()`

julia v0.6.2
PyPlot v3.6.4

**Comment by KentaroTakeda** [comment]
The following code is a sample code in Python (refer to [this page](https://matplotlib.org/2.1.1/gallery/widgets/slider_demo.html)).

`import numpy as np`
`import matplotlib.pyplot as plt`
`from matplotlib.widgets import Slider, Button, RadioButtons`

`fig, ax = plt.subplots()`
`plt.subplots_adjust(left=0.25, bottom=0.25)`
`t = np.arange(0.0, 1.0, 0.001)`
`a0 = 5`
`f0 = 3`
`s = a0*np.sin(2*np.pi*f0*t)`
`l, = plt.plot(t, s, lw=2, color='red')`
`plt.axis([0, 1, -10, 10])`

`axcolor = 'lightgoldenrodyellow'`
`axfreq = plt.axes([0.25, 0.1, 0.65, 0.03], facecolor=axcolor)`
`axamp = plt.axes([0.25, 0.15, 0.65, 0.03], facecolor=axcolor)`

`sfreq = Slider(axfreq, 'Freq', 0.1, 30.0, valinit=f0)`
`samp = Slider(axamp, 'Amp', 0.1, 10.0, valinit=a0)`


`def update(val):`
    `amp = samp.val`
    `freq = sfreq.val`
    `l.set_ydata(amp*np.sin(2*np.pi*freq*t))`
    `fig.canvas.draw_idle()`
`sfreq.on_changed(update)`
`samp.on_changed(update)`

`resetax = plt.axes([0.8, 0.025, 0.1, 0.04])`
`button = Button(resetax, 'Reset', color=axcolor, hovercolor='0.975')`

`def reset(event):`
    `sfreq.reset()`
    `samp.reset()`
`button.on_clicked(reset)`

`rax = plt.axes([0.025, 0.5, 0.15, 0.15], facecolor=axcolor)`
`radio = RadioButtons(rax, ('red', 'blue', 'green'), active=0)`

`def colorfunc(label):`
    `l.set_color(label)`
    `fig.canvas.draw_idle()`
`radio.on_clicked(colorfunc)`

`plt.show()`

Thanks.

**Comment by stevengj** [comment]
In Julia, just do the same thing with translated syntax:
```jl
button[:on_clicked](reset)
```
