### ISSUE TITLE
h = surf(z')

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaPy/PyPlot.jl#362]
creates an error message on 0.7.0-beta.256 and PyPlot v2.6.0. Example:
```
using PyPlot
z = rand(30,40)
figure()
  h = surf(z')
```
However,
```
figure()
  h = surf(permutedims(z))
```
works. 
Intended?

**Comment by stevengj** [comment]
This is happening because `z'` in 0.7 produces an `Adjoint` array type, and PyCall doesn't know how to convert those to a NumPy array so it uses a list of lists.  Probably I should change the fallback in PyCall.

**Comment by PaulSoderlind** [comment]
Thanks for the information. I guess this carries over to plot() and all other functions. In case you decide not to change PyCall/PyPlot, I would suggest adding a line in the README. For 2D plots, it would be to use ````plot(vec(x))```` or similar, and for 3D plots ```surf(copy(z'))``` or similar.

**Comment by PaulSoderlind** [comment]
one more piece of (somewhat related) information: this works on 0.7 but not on 1.0 (since repmat is deprecated)
```
x = 1:10
y = 1:15
figure()
  surf(x,y,copy(rand(10,15)'))
```

The issue: `x` and `y` are not matrices

**Comment by stevengj** [comment]
Closed by https://github.com/JuliaPy/PyCall.jl/pull/653
