### ISSUE TITLE
Overwriting getproperty to get rid of [:whatever]

### ISSUE THREAD

**Issue by crstnbr** [JuliaPy/PyPlot.jl#364]
AFAIU this should be possible in 1.0 now. I am wondering wether someone is on this already. If not I could try to look into it at the JuliaCon Hackathon tomorrow, in which case it would be great to get some input on what changes are necessary.

(I couldn't find an issue about this.)

**Comment by musm** [comment]
If you do work on this it should be in the `PyCall` repo not here. Also see the work https://github.com/ihnorton/PyCall.jl/commit/bd5856d0ecf51633a7fa10491926b5ec1700dba8

**Comment by crstnbr** [comment]
See https://github.com/JuliaPy/PyCall.jl/pull/517
