### ISSUE TITLE
ERROR:ArgumentError: haskey of NULL PyObject

### ISSUE THREAD

**Issue by amerysong** [JuliaPy/PyPlot.jl#369]
I install Pyplot according to the installation guide, but got this error. the stack trace looks like this:
>Stacktrace:
 [1] haskey(::PyCall.PyObject, ::String) at /home/amery/.julia/packages/PyCall/fiJ3o/src/PyCall.jl:297
 [2] #ioff#68(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function) at /home/amery/.julia/packages/PyPlot/jXCXB/src/PyPlot.jl:169
 [3] ioff() at /home/amery/.julia/packages/PyPlot/jXCXB/src/PyPlot.jl:169
 [4] top-level scope at /home/amery/.julia/packages/Plots/LWBTU/src/backends.jl:395
 [5] eval at ./boot.jl:319 [inlined]
 [6] _initialize_backend(::Plots.PyPlotBackend) at /home/amery/.julia/packages/Plots/LWBTU/src/backends.jl:388
 [7] backend(::Plots.PyPlotBackend) at /home/amery/.julia/packages/Plots/LWBTU/src/backends.jl:196
 [8] backend(::Symbol) at /home/amery/.julia/packages/Plots/LWBTU/src/backends.jl:209
 [9] pyplot() at /home/amery/.julia/packages/Plots/LWBTU/src/backends.jl:29
 [10] top-level scope at none:0

**Comment by stevengj** [comment]
That probably indicates that you ignored an error which showed up earlier, complaining about not finding a matplotlib backend or something.

**Comment by jacob-roth** [comment]
In Julia 1.0, I tried the above with no luck.

@stevengj: What does 
```
PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the matplotlib.pyplot module, you can
use `pyimport_conda("matplotlib.pyplot", PKG)`, where PKG is the Anaconda
package the contains the module matplotlib.pyplot, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).
```
mean? I'm not sure what `PKG` is. Alternatively, could you please elaborate on the `Conda.add`?

**Comment by stevengj** [comment]
Try `ENV["MPLBACKEND"]="tkagg"` to try a different backend.

**Comment by jacob-roth** [comment]
I tried `ENV["MPLBACKEND"]="tkagg"` and rebuilt `PyCall` then `PyPlot`, but the error of no GUI seems to be referring to a v0.6 package location, not the current v1.0 directory where I think `Conda` is building mpl.

**Comment by jacob-roth** [comment]
Hm, updating to julia v1.0.2 seemed to fix it

**Comment by stevengj** [comment]
Good to know!  It looks like a C++ standard library conflict, much like issue #219 which arose on CentOS.  What OS are you using?

**Comment by jacob-roth** [comment]
Ah, yes yes, I'm using Ubuntuu 14.04 LTS

**Comment by nlw0** [comment]
> In Julia 1.0, I tried the above with no luck and am still getting the `No working GUI backend found for matplotlib` error.
> 
> @stevengj: In the `ERROR: InitError: PyError (PyImport_ImportModule ` error, what does
> 
> ```
> PyCall is currently configured to use the Julia-specific Python distribution
> installed by the Conda.jl package.  To install the matplotlib.pyplot module, you can
> use `pyimport_conda("matplotlib.pyplot", PKG)`, where PKG is the Anaconda
> package the contains the module matplotlib.pyplot, or alternatively you can use the
> Conda package directly (via `using Conda` followed by `Conda.add` etcetera).
> ```
> mean? I'm not sure what `PKG` is. Alternatively, could you please elaborate on the `Conda.add`?

That help message is quite frustrating, I did manage to install PyPlot at some point when I tried, but the PKG thing makes me feel completely lost, and the "etcetera" shows it's really not intended for beginners... If you google the stuff you can't find any references showing how "obvious" it is either

**Comment by milankl** [comment]
I still kept getting these errors (import, GUI, haskey NULL) even after rebuilding everything. I realized then that sometimes the order of loading different packages matters: Start with PyCall/PyPlot then import weakly supported/deprecated packages solved it for me.

**Comment by smac89** [comment]
The way I fixed this issue was to do the following in Julia REPL:

```
ENV["PYTHON"]=""
Pkg.build("PyCall")
```
Restart the REPL

```
Pkg.add("Conda")
import Conda
Conda.add("matplotlib")
using PyPlot
```

Close the REPL and try using pyplot now

**Comment by arghavanpartovifard** [comment]
In Julia REPL:
│ ```
│ import Pkg;
│ Pkg.add("Conda")
│ import Conda
│ Conda.update()
│ Pkg.build("PyPlot")

**Comment by beamiter** [comment]
> The way I fixed this issue was to do the following in Julia REPL:
> 
> ```
> ENV["PYTHON"]=""
> Pkg.build("PyCall")
> ```
> 
> Restart the REPL
> 
> ```
> Pkg.add("Conda")
> import Conda
> Conda.add("matplotlib")
> using PyPlot
> ```
> 
> Close the REPL and try using pyplot now

great, fixed by this with julia1.6.6
