### ISSUE TITLE
Get 'nbagg' backend working with IJulia

### ISSUE THREAD

**Issue by Gregstrq** [JuliaPy/PyPlot.jl#376]
I know this is a duplicate of JuliaPy/PyPlot.jl#137, but it seems there was no progress since 2015 on this subject (the same applies to the accompanying issue JuliaPy/PyCall.jl#89).

I believe I have at least a vague idea how to solve the issue and I am willing to do it (at least to try), if the mainteners don't have enough time. I just need a bit of help. I wrote about it here https://github.com/JuliaPy/PyPlot.jl/issues/137#issuecomment-404221249, but there was no response in a month.

**Comment by stevengj** [comment]
Thanks for the ping.  Closing as a duplicate.
