### ISSUE TITLE
pcolor():  Warning: The default `strides(a::AbstractArray)` implementation is deprecated .......

### ISSUE THREAD

**Issue by cwb0** [JuliaPy/PyPlot.jl#380]
>julia> versioninfo()
Julia Version 0.7.0
Commit a4cb80f3ed (2018-08-08 06:46 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = "C:\Users\Carsten\AppData\Local\atom\app-1.30.0\atom.exe" -a
  JULIA_NUM_THREADS = 2

**I‘ve got the following warning applying pcolor():**

> julia> pcolor(a1,a2,a3)
┌ Warning: The default `strides(a::AbstractArray)` implementation is deprecated for general arrays.
│ Specialize `strides(::Adjoint)` if `Adjoint` indeed uses a strided representation in memory.
│ Warning: inappropriately implementing this method for an array type that does not use strided
│ storage may lead to incorrect results or segfaults.
│   caller = stride at abstractarray.jl:350 [inlined]
└ @ Core .\abstractarray.jl:350
┌ Warning: The default `strides(a::AbstractArray)` implementation is deprecated for general arrays.
│ Specialize `strides(::Adjoint)` if `Adjoint` indeed uses a strided representation in memory.
│ Warning: inappropriately implementing this method for an array type that does not use strided
│ storage may lead to incorrect results or segfaults.
│   caller = stride at abstractarray.jl:350 [inlined]
└ @ Core .\abstractarray.jl:350
┌ Warning: The default `strides(a::AbstractArray)` implementation is deprecated for general arrays.
│ Specialize `strides(::Adjoint)` if `Adjoint` indeed uses a strided representation in memory.
│ Warning: inappropriately implementing this method for an array type that does not use strided
│ storage may lead to incorrect results or segfaults.
│   caller = ip:0x0
└ @ Core :-1
PyObject <matplotlib.collections.PolyCollection object at 0x0000000026F8EEF0>

with 

> julia> a1
1×64 Adjoint{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}:

> julia> a2
-0.4921875:0.015625:0.4921875

> julia> a3
64×64 Adjoint{Float64,Array{Float64,2}}:

**Comment by cwb0** [comment]
same warnings for

> pcolormesh(a1,a2,a3)

**Comment by Nosferican** [comment]
Still persists (see https://github.com/JuliaLang/julia/pull/25321#issuecomment-421189148 for solution). It is very prevalent when using `p[:ax]` with `::Adjoint`... For now one has to `Matrix(obj')` in order to get it to work.
