### ISSUE TITLE
julia 0.7 segfaults when legend is added

### ISSUE THREAD

**Issue by e-pc** [JuliaPy/PyPlot.jl#392]
OS: archlinux
julia: 0.7
python: Conda package

```
signal (11): Segmentation fault
in expression starting at
PyObject_Call at /home/User/.julia/packages/Conda/m7vem/deps/usr/lib/libpython3.7m.so (unknown line)
unknown function (ip: 0x7ffd78c8961f)
Allocations: 126158263 (Pool: 126152355; Big: 5908); GC: 150
```

**Comment by stevengj** [comment]
I can't reproduce:
```
using PyPlot; plot(rand(10)); legend(["foo"])
```
works for me.

**Comment by e-pc** [comment]
`julia> using PyPlot; plot(rand(10)); legend(["foo"])

signal (11): Segmentation fault
in expression starting at no file:0
PyObject_Call at /home/User/.julia/packages/Conda/m7vem/deps/usr/lib/libpython3.7m.so (unknown line)
unknown function (ip: 0x316c7cf)
Allocations: 11441892 (Pool: 11440128; Big: 1764); GC: 25
Segmentation fault (core dumped)
`
I am getting this on archlinux, however, on windows 10 it works perfectly.

**Comment by e-pc** [comment]
Sorry, I forgot to mention that on archlinux I've tried the same things for PyCall using python2.7 and python3.7 as well (Conda was my last resort). Always the same error is showing up.

**Comment by e-pc** [comment]
Something was wrong with my julia installation. Removed ~/.julia and installed packages again. Now everything works perfectly.
