### ISSUE TITLE
ax.yaxis.set_label_position("right")

### ISSUE THREAD

**Issue by janrpeters** [JuliaPy/PyPlot.jl#395]
I translated
``
ax.yaxis.set_label_position("right")
``
to
``
ax[:yaxis][:set_label_position]("right")
``
but it does not work. Does that feature exist?

**Comment by stevengj** [comment]
Works for me, e.g.
```jl
plot(rand(100))
ax = gca()
ax[:yaxis][:set_label_position]("right")
ylabel("foo")
```
