### ISSUE TITLE
access to histograms failing in Julia 1.0.1

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaPy/PyPlot.jl#396]
Access to histograms no longer works for me and my student...

```julia
using PyPlot
PyPlot[:hist]
```

```julia
import PyPlot; const plt = PyPlot
plt[:hist]
plt[:hist]() # this too fails
```

both give error:
```julia
ERROR: MethodError: no method matching getindex(::Module, ::Symbol)
Stacktrace:
 [1] top-level scope at none:0
```

how do we access the histogram function in Julia 1.0?

**Comment by tkf** [comment]
PyPlot.jl already exports `plt` so it's just:

```julia
using PyPlot
data = 1:10
plt[:hist](data)
```

**Comment by SimonEnsemble** [comment]
@tkf thanks. Should one of us make a pull request to update the `README` for `PyPlot.jl`?

**Comment by tkf** [comment]
You don't need any permission to make a PR!

**Comment by stevengj** [comment]
The current documentation is correct — it doesn't say to use `PyPlot[:hist]`, it says to use `plt[:hist]`.
