### ISSUE TITLE
using PyPlot.axes in module ... conflicts with an existing identifier

### ISSUE THREAD

**Issue by MaxandreJ** [JuliaPy/PyPlot.jl#398]
Hi,

When I import PyPlot using `using PyPlot` I get the following Warning:
`using PyPlot.axes in module ... conflicts with an existing identifier`

After a little search online this seems to be a conflict with Juno. I know I can do `import PyPlot` instead of `using PyPlot` but this feels a little clunky. It would be great if I could use `using PyPlot` without any conflicts with a standard module! Maybe this is rather an issue with Juno though...

Best,
Maxandre

**Comment by gabrielgellner** [comment]
My understanding this is an issue with julia 0.7 / 1.0 taking this name for a standard array operation in Julia, not a Juno issue. It is kind of a tricky problem as it is the standard name in matplotlib for a plotting axes, and given that PyPlot.jl aims to be a literal translation of this api it would need to be somehow shielded like with `plot[:axes]` which could be super inconvenient.

**Comment by MaxandreJ** [comment]
Okay, thanks for letting me know. I suppose that this issue can't reasonably be solved then.

**Comment by tkf** [comment]
I think we should just stop exporting `axes`.  Once https://github.com/JuliaPy/PyCall.jl/pull/517 is merged you can just do `plt.axes()`.

**Comment by stevengj** [comment]
Fixed by c7afdfd64539ff411df565d8b74ed63fcf6aee86
