### ISSUE TITLE
No GUI figure window after matplotlib update

### ISSUE THREAD

**Issue by chakravala** [JuliaPy/PyPlot.jl#404]
After upgrading to `python2-matplotlib-2.2.3-3` from `python2-matplotlib-2.2.3-2` the figure window no longer appears in Julia. I believe it might be related to `pyqt5` being added as a dependency, but I'm not sure. Does anyone know what the cause is or how to fix it?

For now, I am going to stick with the 2.2.3-2 version.

This is the package released on arch linux repositories.

**Comment by stevengj** [comment]
You could try changing your backend by editing `.matplotlibrc` (or setting the MPLBACKEND environment variable).  It sounds like you are on Ubuntu?   Do you get any error message?

I'm using Matplotlib 3.0.1 (installed via Conda) on MacOS, with the qt5agg backend, and it works fine for me.

**Comment by chakravala** [comment]
Hi, I'm actually using arch linux, as I mentioned at the end of my post.

One other thing is I am using `ENV["PYTHON"] = "python2"`, which is why I am on 2.2.3. For python 3 I have the 3.0.1 version, but I have the same issue with that.

Editing `.matplotlibrc` did nothing for me, but changing the environmnet variable MPLBACKEND solved the issue for me, now it works with both python2 and python3. Thanks.
