### ISSUE TITLE
PyPlot missing dependencies?

### ISSUE THREAD

**Issue by cossio** [JuliaPy/PyPlot.jl#408]
I added PyPlot, then try to plot something via Plots.jl, and got an error that I didn't have PyCall installed.

I got a similar error with LaTeXStrings. 

I guess this is related to there being no Project.toml listing these dependencies yet?

**Comment by tkf** [comment]
It's probably:
https://github.com/JuliaPlots/Plots.jl/issues/1672
https://discourse.julialang.org/t/julia-v1-0-install-notes/13583/12

**Comment by tkf** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/1838
