### ISSUE TITLE
TkAgg backend on macOS aborts

### ISSUE THREAD

**Issue by tkf** [JuliaPy/PyPlot.jl#410]
It seems that there are problems using TkAgg in macOS:
https://github.com/JuliaPy/PyPlot.jl/issues/405
https://github.com/JuliaPy/PyPlot.jl/issues/399
https://github.com/JuliaPy/PyPlot.jl/issues/253#issuecomment-441479989
https://discourse.julialang.org/t/pyplot-installation-error-related-to-libpython3-7m-dylib-and-libsystem-kernel-dylib/17649

Upstream issues:
https://github.com/matplotlib/matplotlib/issues/7743
https://sourceforge.net/p/tktoolkit/bugs/3082/

How about removing `:tk` from the list of GUIs to try in macOS? Or maybe move it to the end?

https://github.com/JuliaPy/PyPlot.jl/blob/daadae458ecb696e29c45636d91a9e7b7eddc246/src/init.jl#L50-L60

I also suggest to install `pyqt` in `build.jl` using https://github.com/JuliaPy/PyCall.jl/pull/613

**Comment by stevengj** [comment]
Is this still an issue?  On my MacOS machine PyPlot defaults to `qt5`

**Comment by tkf** [comment]
Reading the conda recipe it still looks like matplotlib does not install pyqt by default? https://github.com/AnacondaRecipes/matplotlib-feedstock/blob/f5ecb6832741888ab853ac92345d9fc4124de5d0/recipe/meta.yaml#L56

Also, the fact that `:tk` comes before `:qt5` means that this problem would pops up once tk is installed via some other dependencies.

But I don't have macOS so I can't check the situation myself.  So, if you (or other macOS users) think it's already fixed then I don't have any reasons to stop closing this issue.

**Comment by stevengj** [comment]
Changed to put `tk` last since this seems to still be an issue.

**Comment by stevengj** [comment]
This seems to be fine these days, at least with the Conda tkinter package which is nowadays the default on MacOS.
