### ISSUE TITLE
twinx not supported in PyPlot

### ISSUE THREAD

**Issue by Bounce00** [JuliaPy/PyPlot.jl#411]
When I try to plot two_scales fig, I used the twinx field, but it not works.

y = rand(20,2)
x = 1:20
pygui(true)
fig,ax1 = subplots()
plot(y[:,1], "b", lw=1.5, label="1st")
ax2=ax1.twinx()
plot(y[:,2], "g", lw=2.0, lable="2nd")

type PyObject has no field twinx

Stacktrace:
 [1] getproperty(::Any, ::Symbol) at .\sysimg.jl:18
 [2] top-level scope at In[2]:11

**Comment by mzaffalon** [comment]
Have you tried `ax1[:twinx]()`?

**Comment by stevengj** [comment]
In the newest PyPlot you can use the dot syntax.
