### ISSUE TITLE
miniconda fully installed by default on macOS unless explicitly set ENV["PYTHON"]

### ISSUE THREAD

**Issue by xdavidliu** [JuliaPy/PyPlot.jl#415]
this behavior is noted in the installation instructions for IJulia for the case in which the user already has jupyter installed through pip or conda, e.g. on macOS one must explicitly first do ENV["JUPYTER"]="jupyter", even if jupyter is already in the PATH, in order for IJulia to use an existing jupyter if it is already installed.

Here, if one already has python and matplotlib installed, then tries to Pkg.add("PyPlot") on macOS, the default behavior is to install the full ~2.0 gb miniconda into ~/.julia, even if python is already in the PATH. In order for PyPlot to use an existing python, it appears that it is necessary to explicitly do ENV["PYTHON"]="python" before adding PyPlot. This doesn't seem to be noted in the installation instructions.

**Comment by stevengj** [comment]
It's noted in the PyCall installation instructions: https://github.com/JuliaPy/PyCall.jl#installation

**Comment by xdavidliu** [comment]
that may be a pitfall / gotcha for people (like myself) who directly install PyPlot, with PyCall being installed automatically as a dependency
