### ISSUE TITLE
PyPlot explicitly asks for Python3.6

### ISSUE THREAD

**Issue by puenka** [JuliaPy/PyPlot.jl#422]
After my distribution recently upgraded to Python3.7, this rendered PyPlot unusable, as it explicitly asks for libpython3.6m.so.1.0 on my machine. I worked around by having Python3.6 installed additionally to the current version.

**Comment by tkf** [comment]
Did you try https://github.com/JuliaPy/PyCall.jl#specifying-the-python-version?

**Comment by puenka** [comment]
This also did fix the issue for me.

**Comment by stevengj** [comment]
PyCall saves the info about your Python configuration; you have to rebuild if you want it to switch.
