### ISSUE TITLE
warning message: `@pyimport foo` is deprecated in favor of `foo = pyimport("foo")`

### ISSUE THREAD

**Issue by cwb0** [JuliaPy/PyPlot.jl#429]
For some time I'v got the following warning message:
Warning: @pyimport foo is deprecated in favor of foo = pyimport("foo").
│ caller = _pywrap_pyimport(::PyObject) at PyCall.jl:400
└ @ PyCall C:\Users\Carsten.julia\packages\PyCall\RQjD7\src\PyCall.jl:400
after importing: @pyimport matplotlib.patches as patch. This is needed to draw filled rectangle.

**Comment by stevengj** [comment]
This is not bug in PyPlot, it is a problem in your code: as the deprecation message says, just do
```jl
patch = pyimport("matplotlib.patches").
```
If you are using PyPlot already, you can also access this module as:
```jl
using PyPlot
patches = PyPlot.matplotlib.patches
```
