### ISSUE TITLE
deprecation warnings back

### ISSUE THREAD

**Issue by gideonsimpson** [JuliaPy/PyPlot.jl#432]
After a recent update (using Julia 1.1), I started getting these sorts of warnings again when using  pyplot (with Julia Plots):
`┌ Warning: `getindex(o::PyObject, s::Symbol)` is deprecated in favor of dot overloading (`getproperty`) so elements should now be accessed as e.g. `o.s` instead of `o[:s]`.
│   caller = py_add_series(::Plots.Plot{Plots.PyPlotBackend}, ::Plots.Series) at pyplot.jl:592
└ @ Plots /Users/guardian/.julia/packages/Plots/QYETN/src/backends/pyplot.jl:592`

**Comment by stevengj** [comment]
Those warnings are not from PyPlot.jl, they are from Plots.jl.  They are fixed in JuliaPlots/Plots.jl#1956, which has not yet been tagged in a release.
