### ISSUE TITLE
It ignores ioff() spectacularly in Jupyter

### ISSUE THREAD

**Issue by kzapfe** [JuliaPy/PyPlot.jl#436]
PyPlot in Julia 1.x.x (1.0.3 and 1.1.0) ignores completely the ioff() instruction. In Jupyter it continues displaying the plots in the notebook. I have tried with various locations of the function in the code, but to no avail yet.

**Comment by stevengj** [comment]
ion and ioff only affect GUI mode (where the plot is displayed in a separate window, and you want to decide whether it is immediately updated after every command), not inline plotting mode.  I think it's the same in Python/IPython with inline plotting..
