### ISSUE TITLE
This is #410 — tkagg is broken (upstream bug) on MacOS, and you need to use a non-tk backend.

### ISSUE THREAD

**Issue by liuyoufang** [JuliaPy/PyPlot.jl#442]
I also tried to changed the backend to Qt5agg and macosx, which is still not working apparently

This is #410 — tkagg is broken (upstream bug) on MacOS, and you need to use a non-tk backend.

Are you using the Conda Python?   (What is `PyPlot.PyCall.python`?) Conda can automatically install the qt backend for you.

_Originally posted by @stevengj in https://github.com/JuliaPy/PyPlot.jl/issues/441#issuecomment-491627324_

**Comment by stevengj** [comment]
Please don't post duplicate issues.
