### ISSUE TITLE
Julia 1.20 and PyPlot.svg(true)

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaPy/PyPlot.jl#455]
on Windows 10 64, Julia 1.2.0, the following crashes jupyter 
```
using PyPlot
PyPlot.svg(true)
figure()
plot(1:10)
```

Without  ```PyPlot.svg(true)```, it works well. 

 
EDIT: "crashes" is perhaps too strong. But it unhinges and scrambles the jupyter menu so that it becomes useless.

**Comment by stevengj** [comment]
I can't reproduce — your example works fine for me.  (MacOS, Chrome browser.)

What browser are you using?

**Comment by PaulSoderlind** [comment]
Firefox and Chrome (latest versions) both produce this.

**Comment by PaulSoderlind** [comment]
I cannot reproduce this after the latest updates or Firefox and Chrome. Consider it solved.
