### ISSUE TITLE
view_init not defined

### ISSUE THREAD

**Issue by mancolric** [JuliaPy/PyPlot.jl#464]
I am trying to rotate a 3D figure --created with `plot_trisurf`-- with [`view_init`](https://matplotlib.org/3.1.1/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.html). I have previously called  `using_3D()`. However, I get the following error:

'view_init not defined'

If I modify plot3d.jl from 

`const mplot3d_funcs = (:bar3d, :contour3D, :contourf3D, :plot3D, :plot_surface,
                       :plot_trisurf, :plot_wireframe, :scatter3D,
                       :text2D, :text3D)`

to 

`const mplot3d_funcs = (:bar3d, :contour3D, :contourf3D, :plot3D, :plot_surface,
                       :plot_trisurf, :plot_wireframe, :scatter3D,
                       :text2D, :text3D, :view_init)`

the problem is fixed.

**Comment by stevengj** [comment]
Thanks, a PR to add this function to the list of exported symbols (maybe also `voxels`) would be welcome.

**Comment by mancolric** [comment]
[Done](https://github.com/JuliaPy/PyPlot.jl/pull/465).

**Comment by stevengj** [comment]
Closed by #465
