### ISSUE TITLE
pyplot() won't compile with fedora 32

### ISSUE THREAD

**Issue by AndrewLyasoff** [JuliaPy/PyPlot.jl#484]
After upgrade from Fedora 31 to Fedora 32, PyPlot.jl no longer works in either Julia 1.4.0 or Julia 1.4.1. The error message reads:

[ Info: Precompiling PyPlot [d330b81b-6aea-500a-939a-2ce795aea3ee]
ERROR: LoadError: InitError: could not load library "/usr/lib64/libpython3.7m.so.1.0"
/usr/lib64/libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
Stacktrace: ...

Simply placing libpython3.7m.so.1.0 in /usr/lib64 does not resolve the problem.
This may be related to the fact that Fedora 32 comes with python 3.8.

**Comment by AndrewLyasoff** [comment]
Completely removing .julia solves the issue.

**Comment by stevengj** [comment]
Probably you just needed to re-run `build PyCall`, to update its configuration to use your new Python version.

**Comment by AndrewLyasoff** [comment]
Thank you very much for your response. Yes, this is what I did, but it was
a situation I have not encountered before. In addition, the old .julia is
still to be removed, together with .cache/matplotlib.

Thank you again,
Andrew
