### ISSUE TITLE
Feature request: interactive mode

### ISSUE THREAD

**Issue by marius311** [JuliaPy/PyPlot.jl#495]
From a Python notebook in Jupyterlab you can enable "widget" mode and get a plot which is interactive, ie can be zoomed, etc.. Could something like this be possible with PyPlot?

![image](https://user-images.githubusercontent.com/1510968/90333821-cce9c580-df7d-11ea-8fdd-60555238363f.png)

**Comment by stevengj** [comment]
`pygui(true)` does this.

**Comment by stevengj** [comment]
Oh, sorry, you are asking about the widget backend.  That is https://github.com/JuliaPy/PyCall.jl/issues/89
