### ISSUE TITLE
PyPlot Slows to halt : conflict with control flow ?

### ISSUE THREAD

**Issue by houchmandzadeh** [JuliaPy/PyPlot.jl#503]
After a system crash, I installed Ubuntu 20.04.1 and installed julia 1.4.1 from Ubuntu repository. PyPlot has now a strange behavior. 
Plotting works perfectly and repeatedly. But if I try a loop, then pyplot stops nearly completely. Even if the plotting is not inside the loop, for example 
--------------------------
clf()
for i=1:50
    print(2*i,"\n")
end
----------------------
takes suddenly more than a minute the first time, and then nearly halts the second time. Even if the second time, no loop is involved and the instruction is simply 
plot(x,y)

The issue is not related to jupyter notebook and is reproduced in REPL.

**Comment by houchmandzadeh** [comment]
Apparently, the problem was the backend. Installing qt5 and setting
pygui(:qt5)

Solved the problem.

**Comment by stevengj** [comment]
What backend was it using before?
