### ISSUE TITLE
axis label rotation does not work

### ISSUE THREAD

**Issue by HenriDeh** [JuliaPy/PyPlot.jl#511]
As a MWE I'll just leave a link to the documentation of Plots for PyPlot:

http://docs.juliaplots.org/latest/generated/pyplot/#pyplot-ref29

This very example uses xrotation = 90 but labels are not rotated.

**Comment by stevengj** [comment]
The PyPlot/matplotlib interface works for me, e.g.
```jl
plot(rand(100,6))
xticks(rotation=60)
```
produces
![image](https://user-images.githubusercontent.com/2913679/101070817-d79a8b80-3569-11eb-984c-d4c0d96c511f.png)
So, if it doesn't work in Plots, that sounds like a bug in Plots.jl and should be reported there.
