### ISSUE TITLE
How can I suppress the automatic figure output in the Jupyter notebook?

### ISSUE THREAD

**Issue by metorm** [JuliaPy/PyPlot.jl#516]
I am not sure if this is a bug or it's just that I am stupid.

I am currently using `PyPlot.jl` via IJulia & Jupyter lab. I'd like the figures produced by `PyPlot.jl` **only** shows up after I call `display(fig)`. However, the figures are always rendered right after the cell in which `plot()` is called.

I looked up for 3 hours and tried the following:

```
plt.ioff();
ioff();
PyPlot.ioff();
PyPlot.matplotlib.pyplot.ioff()

# add ; after the plot statment
```

After each try, I did a clean kernel restart. The problem is not settled yet. Thank you for any suggestions.

![image](https://user-images.githubusercontent.com/12082680/107124888-446f3080-68e1-11eb-8a94-675e7580c78d.png)

**Comment by stevengj** [comment]
I'm not perfectly clear on what semantics you want, but you can do:
```jl
PyPlot.isjulia_display[] = false
```

**Comment by metorm** [comment]
Thank you @stevengj, `PyPlot.isjulia_display[] = false` does prevent figures from being automatically displayed.

But now I am faced with another newbie problem: after `PyPlot.isjulia_display[] = false`, how can I actually show this figure in another cell? I tried `display()` & `show()` but no luck.

![image](https://user-images.githubusercontent.com/12082680/107133606-efeda480-6924-11eb-9e9c-6465b22817b8.png)

**Comment by metorm** [comment]
Well, via further searching now I know the above `a` is a `matplotlib.lines.Line2D` object, well I need a `fig::PyFigure` object to show is in `jupyter`.

However, the only approach to get a `fig::PyFigure` object documented is `gcf()`. Obviousely if you have several plots you cannot simply use `gcf()`.

Any ideas? @stevengj

**Comment by stevengj** [comment]
Use `fig = figure()` to explicitly create the figure object for later use.

**Comment by metorm** [comment]
@stevengj Hmm, now I get some internal logic of it ...

![image](https://user-images.githubusercontent.com/12082680/107165227-33134a80-69ed-11eb-87b8-72b70b8201c6.png)

I finally made it work as above. Thanks a lot.

BTW, if I already have a `matplotlib.lines.Line2D`, which is not built from a `figure()` object, is it possible to translate it to a display-ready figure object?

**Comment by stevengj** [comment]
> BTW, if I already have a matplotlib.lines.Line2D, which is not built from a figure() object, is it possible to translate it to a display-ready figure object?

I'm not sure off the top of my head; you'd have to dig through the matplotlib docs.

**Comment by stevengj** [comment]
(You shouldn't need to explicitly `clear` the figure after it is created.)

**Comment by metorm** [comment]
OK, got it.

I wrote the `fig.clear()` statment since the cell in jupter notebook may be executed for multi times. Without the `clear()` the previouse plot would overlap with newer plots.
