### ISSUE TITLE
ModuleNotFoundError("No module named 'matplotlib'")

### ISSUE THREAD

**Issue by rafaqz** [JuliaPy/PyPlot.jl#521]
Loading PyPlot.jl with `pyplot()` from plots is giving this error, on both Ubuntu and Macos with Julia v1.6.

PyPlot version is 2.9.0. It seems to precompile ok but errors, I think on `pyplot()`:

Edit: Ok I just realised that ENV["PYTHON"]="" is required. The problem is this is all in a Manifest.toml file... so we need to add that line before `instantiate`. Has there been any thought to swapping this behaviour?

```julia
ERROR: LoadError: InitError: PyError (PyImport_ImportModule

The Python package matplotlib could not be imported by pyimport. Usually this means
that you did not install matplotlib in the Python version being used by PyCall.

PyCall is currently configured to use the Python version at:

/usr/bin/python3

and you should use whatever mechanism you usually use (apt-get, pip, conda,
etcetera) to install the Python package containing the matplotlib module.

One alternative is to re-configure PyCall to use a different Python
version on your system: set ENV["PYTHON"] to the path/name of the python
executable you want to use, run Pkg.build("PyCall"), and re-launch Julia.

Another alternative is to configure PyCall to use a Julia-specific Python
distribution via the Conda.jl package (which installs a private Anaconda
Python distribution), which has the advantage that packages can be installed
and kept up-to-date via Julia.  As explained in the PyCall documentation,
set ENV["PYTHON"]="", run Pkg.build("PyCall"), and re-launch Julia. Then,
To install the matplotlib module, you can use `pyimport_conda("matplotlib", PKG)`,
where PKG is the Anaconda package that contains the module matplotlib,
or alternatively you can use the Conda package directly (via
`using Conda` followed by `Conda.add` etcetera).

) <class 'ModuleNotFoundError'>
ModuleNotFoundError("No module named 'matplotlib'")

Stacktrace:
  [1] pyimport(name::String)
    @ PyCall ~/.julia/packages/PyCall/tqyST/src/PyCall.jl:547
  [2] pyimport_conda(modulename::String, condapkg::String, channel::String)
    @ PyCall ~/.julia/packages/PyCall/tqyST/src/PyCall.jl:705
  [3] pyimport_conda
    @ ~/.julia/packages/PyCall/tqyST/src/PyCall.jl:704 [inlined]
  [4] __init__()
    @ PyPlot ~/.julia/packages/PyPlot/XHEG0/src/init.jl:179
  [5] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:674
  [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:760
  [7] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:998
  [8] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:914
  [9] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:901
 [10] top-level scope
    @ ~/.julia/packages/Plots/YicDu/src/backends.jl:505
 [11] eval
    @ ./boot.jl:360 [inlined]
 [12] _initialize_backend(#unused#::Plots.PyPlotBackend)
    @ Plots ~/.julia/packages/Plots/YicDu/src/backends.jl:504
 [13] backend
    @ ~/.julia/packages/Plots/YicDu/src/backends.jl:174 [inlined]
 [14] pyplot(; kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Plots ~/.julia/packages/Plots/YicDu/src/backends.jl:31
 [15] pyplot()
    @ Plots ~/.julia/packages/Plots/YicDu/src/backends.jl:31
 [16] top-level scope
    @ ~/work/SpatialMechanisticModellingInJulia/SpatialMechanisticModellingInJulia/src/plots.jl:3
 [17] include(fname::String)
    @ Base.MainInclude ./client.jl:444
 [18] top-level scope
    @ none:1
during initialization of module PyPlot

**Comment by BoundaryValueProblems** [comment]
I have exactly the same problem on my Macs after I upgraded to Julia v1.6.0.
`matplotlib` is already installed via Conda, and `Conda.list()` shows this. Yet it still try to install `matplotlib` somehow.
Interestingly enough, my Windows machine doesn't have this problem with PyPlot.

**Comment by BoundaryValueProblems** [comment]
I have some update. After wiping out ~/.julia/conda on my MacBook Pro, and rebuilding it via `Pkg.build("PyCall")`, at least PyPlot.jl is working! But the pyplot backend of Plots.jl is not working yet. So, I'll file the issue at Plots.jl instead of doing it here.

**Comment by BoundaryValueProblems** [comment]
@stevengj ; I resolved the problem of the pyplot backend of Plots.jl, but it is not yet perfect due to some warning message. I just posted my resolution at https://github.com/JuliaPlots/Plots.jl/issues/3416
And I would greatly appreciate if you could say why this problem (macOS specific) occurs.
Thank you very much!

**Comment by stevengj** [comment]
The problem is that you had configured PyCall to use your system Python `/usr/bin/python3` (which didn't have matplotlib), so installing things using Conda.jl (which installs its own Python distro) didn't help. 

(Presumably you had set `ENV["PYTHON"]="/usr/bin/python3"` at some point before installing/building PyCall, to tell it to use your system Python.  Once you configure PyCall to use a particular Python, it remembers it in the future, until you force the setting to change by setting `ENV["PYTHON"]` to something else and re-building.)

See also https://github.com/JuliaPy/PyCall.jl#specifying-the-python-version

**Comment by BoundaryValueProblems** [comment]
@stevengj ; thanks for your comments. However, I have never set `ENV["PYTHON"]="/usr/bin/python3"` myself. 
Anyways, after rebuilding ~/.julia/cond folder via `ENV["PYTHON"]=""; Pkg.buld("PyCall")`, why am I encounter all these problems, such as the MKL stuff, removing and adding `numpy`, and the warning message:
```
objc[51561]: Class RunLoopModeTracker is implemented in both /Users/xxx/.julia/artifacts/ee74d003b12e6dd5f748e8cefb1688edbdfb184b/lib/QtCore.framework/Versions/5/QtCore (0x158162aa8) and /Users/xxx/.julia/conda/3/lib/libQt5Core.5.dylib (0x178293a80). One of the two will be used. Which one is undefined.
┌ Warning: No working GUI backend found for matplotlib
└ @ PyPlot ~/.julia/packages/PyPlot/XHEG0/src/init.jl:165
```
as I described in https://github.com/JuliaPlots/Plots.jl/issues/3416 ? Is there anyway to resolve this warning, i.e., specifying only one place of "Class RunLoopModeTracker"?
Thanks!

**Comment by stevengj** [comment]
> However, I have never set ENV["PYTHON"]="/usr/bin/python3" myself.

If you are on Linux that is the default.

**Comment by stevengj** [comment]
The
```
objc[51561]: Class RunLoopModeTracker is implemented in both /Users/xxx/.julia/artifacts/ee74d003b12e6dd5f748e8cefb1688edbdfb184b/lib/QtCore.framework/Versions/5/QtCore (0x158162aa8) and /Users/xxx/.julia/conda/3/lib/libQt5Core.5.dylib (0x178293a80). One of the two will be used. Which one is undefined.
```
error sounds like a conflict between the Julia Qt package (which presumably you installed for some Julia GUI package) and the Conda one.   You can try using a different Matplotlib backend by setting the MPLBACKEND environment variable, or uninstalling your Julia Qt package.
