### ISSUE TITLE
gridspec_kw for subplot ?

### ISSUE THREAD

**Issue by zejian-li** [JuliaPy/PyPlot.jl#524]
In python one can do 
```
import numpy as np
import matplotlib.pyplot as plt 

# generate some data
x = np.arange(0, 10, 0.2)
y = np.sin(x)

# plot it
f, (a0, a1) = plt.subplots(1, 2, gridspec_kw={'width_ratios': [3, 1]})
a0.plot(x, y)
a1.plot(y, x)

f.tight_layout()
f.savefig('grid_figure.pdf')
```
to specify the `gridspec_kw` kw argument, and produce the following plot
![image](https://user-images.githubusercontent.com/24532267/120178717-12743800-c20a-11eb-866c-30dc58742ed9.png)

 How does this translate in Julia ?

**Comment by djohn134** [comment]
It works the same. I.e. in Julia the above would be `gridspec_kw=Dict("width_ratios" => [3,1])`

**Comment by huixinzhang** [comment]
In julia, need another package PyCall. The whole code goes like:
using PyPlot
using PyCall
subplots(1, 2,gridspec_kw=Dict("width_ratios" => [3,1]))
