### ISSUE TITLE
Move to stable matplotlib version

### ISSUE THREAD

**Issue by isentropic** [JuliaPy/PyPlot.jl#527]
The current stable version is 3.4.2 is there a way to get auto-installation (via Conda.jl) to move to 3.4.2?

**Comment by PaulSoderlind** [comment]
Not sure that is a good idea, until PyPlot.jl has been "renovated" to handle some of the new thinks in matplotlib 3.4. See [issue 532](https://github.com/JuliaPy/PyPlot.jl/issues/532)

**Comment by isentropic** [comment]
Actually, pyplot.jl already installs 3.4 matplotlib so I think this a notice, not a request anymore
