### ISSUE TITLE
PyPlot broken under 1.7?

### ISSUE THREAD

**Issue by bardo84** [JuliaPy/PyPlot.jl#543]
Please see [https://discourse.julialang.org/t/pyplot-broken-under-1-7/72971](https://discourse.julialang.org/t/pyplot-broken-under-1-7/72971)

**Comment by PallHaraldsson** [comment]
@bardo84, I would close this issue, as PyPlot seems working (on Linux), unless you know there's an issue (for non-Linux). I answered at discourse.

I could have sworn I saw this issue, maybe it was just moved here. Anyway even if a real problem with the package or some package, it's likely PyCall, so should be moved there?

**Comment by bardo84** [comment]
Agree, thx again!

**Comment by stevengj** [comment]
As commented on discourse, the problem was apparently in installing Python itself, i.e. related to Conda.jl, not to PyCall or PyPlot.
