### ISSUE TITLE
No working GUI backend found for matplotlib

### ISSUE THREAD

**Issue by andrersimoes** [JuliaPy/PyPlot.jl#558]
I can't change PyPlot's backend  from :tk to :qt5 after a fresh install:

> bash> julia
> julia>  using PyCall
> julia>  pygui( :qt5 )
>
> julia> pyimport( "matplotlib" )
> PyObject <module 'matplotlib' from '/home/simoes/.local/lib/python3.10/site-packages/matplotlib/__init__.py'>
>
> julia> pyimport( "PyQt5" )
> PyObject <module 'PyQt5' from '/usr/lib64/python3.10/site-packages/PyQt5/__init__.py'>
>
> julia> using PyPlot
> ┌ Warning: No working GUI backend found for matplotlib
>└ @ PyPlot ~/.julia/packages/PyPlot/NsAWt/src/init.jl:153

My configuration:
1. OpenSuse tumbleweed.
2. pyqt 5.15.7
3. matplotlib 3.5.2

PS: PyQt5 backend works fine when directly called from python command prompt.

My installation steps are:

1. rm -rf .julia to avoid old trash;
2. open julia;
3. define ENV[ "PYTHON"] = "/usr/bin/python3.10";
4. add package PyCall;
5. add package PyPlot;
6. attempt to use as :tk success;
7. restart julia
8. include PyCall
9. change backend to :qt5
10. include PyPlot
11. backend not available.

Any suggestions ?

**Comment by stevengj** [comment]
You definitely should *not* do `pyimport("matplotlib")` before doing `using PyPlot` — importing matplotlib initializes it, and it won't subsequently be possible to change backends.  What happens if you do just:
```jl
ENV["MPLBACKEND"]="Qt5Agg"
using PyPlot
```

**Comment by andrersimoes** [comment]
Hi Steve, didn't know about it. I was just trying to show you that the required packages (matplotlib and qt) are installed on my system. But even without calling pyimport, the results are the same.

Starting julia from scratch and changing the backend using ENV["MPLBACKEND"]="Qt5Agg" before using the package also leads to the same warning.

**Comment by andrersimoes** [comment]
Hi Steve, i tried to:

1. force gui = :qt5 inside PyCall source code gui.jl;
2. do several prints inside find_backend.
3. print the exception from the try catch block inside find_backend.

This happens:
> bash> julia
> julia> using PyCall
> julia> PyCall.gui
> :qt5
> julia> using PyPlot
> find_backend 1
> find_backend 2
> find_backend 3 qt5agg
> find_backend 5
> find_backend 6
> find_backend 6.1
> exception UndefVarError(:gui)
> find_backend 13
> ┌ Warning: No working GUI backend found for matplotlib
> └ @ PyPlot ~/.julia/packages/PyPlot/NsAWt/src/init.jl:178

Sounds like PyPlot cannot find PyCall.gui

My init.jl goes attached as a text file so you can see where are my println's:
[init.txt](https://github.com/JuliaPy/PyPlot.jl/files/9700574/init.txt)

**Comment by andrersimoes** [comment]
Hi Steve, 

I could fix the problem after doing some extra prints inside find_backend, upgrading pip and installing **PySide2**:

> # python3 -m pip install --upgrade pip
> ... # reinstallation of PyQt5
> # pip3 install -U PySide2

The strange part was that PyQt5 was already installed at my machine.

Last exception goes attached for reference.
[exception.txt](https://github.com/JuliaPy/PyPlot.jl/files/9706648/exception.txt)
