### ISSUE TITLE
The show() method doesn't seem to work.

### ISSUE THREAD

**Issue by marlloseff** [JuliaPy/PyPlot.jl#561]
Hello everybody! I used show() to re-show a plot that was closed. In Julia 1.8.3 it doesn't seem to work anymore.
x = plot(rand(10), rand(10))
# close the window
show() # out: empty
x # out: 1-element Vector{PyCall.PyObject}:
  PyObject <matplotlib.lines.Line2D object at 0x7faecfddfd30>
show(x) # out: PyCall.PyObject[PyObject <matplotlib.lines.Line2D object at 0x7faecfddfd30>]
display(x) # out: equal to x

Note: I had to install PyCall with the ENV["PYTHON"]="" option

**Comment by stevengj** [comment]
That's not how Matplotlib works.

If you are using the GUI, then [closing the figure deletes it](https://stackoverflow.com/questions/9621017/matplotlib-re-open-a-closed-figure).

If you are using some other interface, e.g. vscode or IJulia/Jupyter, then you can call `display(fig)` on the figure object.   However, the return value of `plot` is *not* the figuer object.   You can get the figure object from `x[1].figure` or `gcf()`.

**Comment by marlloseff** [comment]
I am using bash terminal. When I type x[1].figure, the output in the terminal is: Figure(PyObject <Figure size 640x480 with 1 Axes>), but without showing the graph. When I type gcf(), a blank figure appears. I remember re-displaying the graphics (Julia 1.7.2) with just the show() command.

**Comment by marlloseff** [comment]
I am using bash terminal. When I type x[1].figure, the output in the terminal is: Figure(PyObject <Figure size 640x480 with 1 Axes>), but without showing the graph. When I type gcf(), a blank figure appears. I remember re-displaying the graphics (Julia 1.7.2) with just the show() command.
